/**
 * Dropdown options for the application
 * All select/dropdown values are defined here for reusability
 */

import type { SelectOption } from "@/components/dynamic/CustomSelect";

export const yesOrNoOptions: SelectOption[] = [
  { label: "Yes", value: "yes" },
  { label: "No", value: "no" },
];

export const companyOrHome: SelectOption[] = [
  { label: "Company Trading Address", value: "company" },
  { label: "Personal address", value: "home" },
  { label: "New Address", value: "new" },
];

export const buyOrRentOptions: SelectOption[] = [
  { label: "Rent", value: "rent" },
  { label: "Buy", value: "buy" },
];

// export const provinceOptions: SelectOption[] = [
//   { value: "ZAF.GP", label: "Gauteng" },
//   { value: "ZAF.WC", label: "Western Cape" },
//   { value: "ZAF.KZN", label: "KwaZulu-Natal" },
//   { value: "ZAF.EC", label: "Eastern Cape" },
//   { value: "ZAF.FS", label: "Free State" },
//   { value: "ZAF.LP", label: "Limpopo" },
//   { value: "ZAF.MP", label: "Mpumalanga" },
//   { value: "ZAF.NW", label: "North West" },
//   { value: "ZAF.NC", label: "Northern Cape" },
// ];

export const cityOptions: SelectOption[] = [
  { value: "johannesburg", label: "Johannesburg" },
  { value: "cape-town", label: "Cape Town" },
  { value: "durban", label: "Durban" },
  { value: "pretoria", label: "Pretoria" },
  { value: "port-elizabeth", label: "Port Elizabeth" },
];

export const businessTypeOptions: SelectOption[] = [
  { value: "sole-proprietor", label: "Sole Proprietor/Other" },
];

export const addressOptions: SelectOption[] = [
  { value: "same", label: "Same as residential address" },
  { value: "different", label: "Different address" },
];

// export const countryOptions: SelectOption[] = [
//   { value: "ZA", label: "South Africa" },
//   { value: "US", label: "United States" },
//   { value: "GB", label: "United Kingdom" },
//   { value: "CA", label: "Canada" },
//   { value: "AU", label: "Australia" },
//   { value: "NZ", label: "New Zealand" },
//   { value: "ZW", label: "Zimbabwe" },
//   { value: "BW", label: "Botswana" },
//   { value: "NA", label: "Namibia" },
//   { value: "MZ", label: "Mozambique" },
//   { value: "LS", label: "Lesotho" },
//   { value: "SZ", label: "Eswatini" },
// ];

export const nationalityOptions: SelectOption[] = [
  { value: "ZA", label: "South African" },
  { value: "US", label: "American" },
  { value: "GB", label: "British" },
  { value: "CA", label: "Canadian" },
  { value: "AU", label: "Australian" },
  { value: "NZ", label: "New Zealander" },
  { value: "ZW", label: "Zimbabwean" },
  { value: "BW", label: "Motswana" },
  { value: "NA", label: "Namibian" },
  { value: "MZ", label: "Mozambican" },
  { value: "LS", label: "Basotho" },
  { value: "SZ", label: "Swazi" },
];

export const bbbeeContributionLevelOptions: SelectOption[] = [
  { value: "level-1", label: "Level 1" },
  { value: "level-2", label: "Level 2" },
  { value: "level-3", label: "Level 3" },
  { value: "level-4", label: "Level 4" },
  { value: "level-5", label: "Level 5" },
  { value: "level-6", label: "Level 6" },
  { value: "level-7", label: "Level 7" },
  { value: "level-8", label: "Level 8" },
  { value: "non-compliant", label: "Non-Compliant" },
];

export const blackWomanOwnershipOptions: SelectOption[] = [
  { value: "0-25", label: "0% - 25%" },
  { value: "26-50", label: "26% - 50%" },
  { value: "51-75", label: "51% - 75%" },
  { value: "76-100", label: "76% - 100%" },
];

export const entityClassificationOptions: SelectOption[] = [
  { value: "financial-institution", label: "Financial Institution" },
  { value: "non-financial-entity", label: "Non-Financial Entity" },
  { value: "active-nfe", label: "Active NFE" },
  { value: "passive-nfe", label: "Passive NFE" },
];

export const businessFundingOptions: SelectOption[] = [
  { value: "personal-savings", label: "Personal Savings" },
  { value: "bank-loan", label: "Bank Loan" },
  { value: "investors", label: "Investors" },
  { value: "family-friends", label: "Family/Friends" },
  { value: "grants", label: "Grants" },
  { value: "other", label: "Other" },
];

export const amountRangeOptions: SelectOption[] = [
  { value: "0-5000", label: "R 0 - R 5,000" },
  { value: "5001-10000", label: "R 5,001 - R 10,000" },
  { value: "10001-25000", label: "R 10,001 - R 25,000" },
  { value: "25001-50000", label: "R 25,001 - R 50,000" },
  { value: "50001-100000", label: "R 50,001 - R 100,000" },
  { value: "100001+", label: "R 100,001+" },
];

export const taxResidencyReasonOptions: SelectOption[] = [
  { value: "not-required", label: "Not required to obtain" },
  { value: "unable-to-obtain", label: "Unable to obtain" },
  { value: "other", label: "Other" },
];

export const machineOptions: SelectOption[] = [
  { value: "1", label: "1" },
  { value: "2", label: "2" },
  { value: "3", label: "3" },
  { value: "4", label: "4" },
  { value: "5", label: "5" },
];

export const deliveryTypeOptions: SelectOption[] = [
  { value: "standard", label: "Standard Delivery" },
  { value: "express", label: "Express Delivery" },
];

export const businessNatureOptions: SelectOption[] = [
  { value: "retail", label: "Retail" },
  { value: "wholesale", label: "Wholesale" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "services", label: "Services" },
  { value: "hospitality", label: "Hospitality & Food" },
  { value: "construction", label: "Construction" },
  { value: "agriculture", label: "Agriculture" },
  { value: "transport", label: "Transport & Logistics" },
  { value: "technology", label: "Technology & IT" },
  { value: "healthcare", label: "Healthcare" },
  { value: "education", label: "Education & Training" },
  { value: "financial-services", label: "Financial Services" },
  { value: "real-estate", label: "Real Estate" },
  { value: "professional-services", label: "Professional Services" },
  { value: "automotive", label: "Automotive" },
  { value: "entertainment", label: "Entertainment & Media" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "energy", label: "Energy & Utilities" },
  { value: "mining", label: "Mining & Quarrying" },
  { value: "other", label: "Other" },
];

// export const businessIndustryOptions: SelectOption[] = [
//   // Agriculture, forestry and fishing
//   { value: "agriculture", label: "Agriculture & Farming" },
//   { value: "forestry", label: "Forestry" },
//   { value: "fishing", label: "Fishing & Aquaculture" },

//   // Mining and quarrying
//   { value: "mining-coal", label: "Coal Mining" },
//   { value: "mining-metal", label: "Metal Ore Mining" },
//   { value: "mining-other", label: "Other Mining" },

//   // Manufacturing
//   { value: "food-manufacturing", label: "Food Manufacturing" },
//   { value: "beverage-manufacturing", label: "Beverage Manufacturing" },
//   { value: "textile-manufacturing", label: "Textile Manufacturing" },
//   { value: "clothing-manufacturing", label: "Clothing Manufacturing" },
//   { value: "leather-manufacturing", label: "Leather Goods Manufacturing" },
//   { value: "wood-manufacturing", label: "Wood Products Manufacturing" },
//   { value: "paper-manufacturing", label: "Paper Manufacturing" },
//   { value: "printing", label: "Printing & Publishing" },
//   { value: "chemical-manufacturing", label: "Chemical Manufacturing" },
//   { value: "pharmaceutical-manufacturing", label: "Pharmaceutical Manufacturing" },
//   { value: "rubber-plastic-manufacturing", label: "Rubber & Plastic Manufacturing" },
//   { value: "metal-manufacturing", label: "Metal Manufacturing" },
//   { value: "electronics-manufacturing", label: "Electronics Manufacturing" },
//   { value: "electrical-equipment", label: "Electrical Equipment Manufacturing" },
//   { value: "machinery-manufacturing", label: "Machinery Manufacturing" },
//   { value: "motor-vehicle-manufacturing", label: "Motor Vehicle Manufacturing" },
//   { value: "furniture-manufacturing", label: "Furniture Manufacturing" },

//   // Electricity, gas, steam
//   { value: "electricity-supply", label: "Electricity Supply" },
//   { value: "water-supply", label: "Water Supply & Sanitation" },

//   // Construction
//   { value: "construction-buildings", label: "Building Construction" },
//   { value: "civil-engineering", label: "Civil Engineering" },
//   { value: "construction-specialized", label: "Specialized Construction" },

//   // Wholesale and retail trade
//   { value: "motor-vehicle-sales", label: "Motor Vehicle Sales & Repair" },
//   { value: "wholesale-trade", label: "Wholesale Trade" },
//   { value: "retail-trade", label: "Retail Trade" },

//   // Transportation and storage
//   { value: "land-transport", label: "Land Transport" },
//   { value: "water-transport", label: "Water Transport" },
//   { value: "air-transport", label: "Air Transport" },
//   { value: "warehousing", label: "Warehousing & Storage" },

//   // Accommodation and food
//   { value: "accommodation", label: "Accommodation Services" },
//   { value: "food-service", label: "Food Service Activities" },

//   // Information and communication
//   { value: "publishing", label: "Publishing Activities" },
//   { value: "broadcasting", label: "Broadcasting" },
//   { value: "telecommunications", label: "Telecommunications" },
//   { value: "it-services", label: "IT Services & Software" },
//   { value: "information-services", label: "Information Services" },

//   // Financial and insurance
//   { value: "financial-services", label: "Financial Services" },
//   { value: "insurance", label: "Insurance" },
//   { value: "financial-auxiliary", label: "Financial Auxiliary Services" },

//   // Real estate
//   { value: "real-estate", label: "Real Estate Activities" },

//   // Professional, scientific and technical
//   { value: "legal-accounting", label: "Legal & Accounting Services" },
//   { value: "consulting", label: "Management Consulting" },
//   { value: "architecture-engineering", label: "Architecture & Engineering" },
//   { value: "research-development", label: "Research & Development" },
//   { value: "advertising", label: "Advertising & Marketing" },
//   { value: "veterinary", label: "Veterinary Services" },

//   // Administrative and support
//   { value: "rental-leasing", label: "Rental & Leasing" },
//   { value: "employment-services", label: "Employment Services" },
//   { value: "travel-services", label: "Travel Agency Services" },
//   { value: "security-services", label: "Security Services" },
//   { value: "facilities-services", label: "Facilities Management" },
//   { value: "office-support", label: "Office Support Services" },

//   // Education
//   { value: "education", label: "Education & Training" },

//   // Health and social work
//   { value: "healthcare", label: "Healthcare Services" },
//   { value: "social-work", label: "Social Work Activities" },

//   // Arts, entertainment and recreation
//   { value: "arts-entertainment", label: "Arts & Entertainment" },
//   { value: "gambling", label: "Gambling & Betting" },
//   { value: "sports-recreation", label: "Sports & Recreation" },

//   // Other service activities
//   { value: "membership-organizations", label: "Membership Organizations" },
//   { value: "repair-services", label: "Repair Services" },
//   { value: "personal-services", label: "Personal Services" },

//   // Other
//   { value: "other", label: "Other" },
// ];



/** Sheet: Branch  and bank names */
export const branchAndBankNamesOptions: SelectOption[] = [
  { label: "NEDBANK LIMITED", value: "198765" },
  { label: "CITIBANK N.A. SOUTH AFRICA", value: "350005" },
  { label: "STANDARD BANK", value: "51001" },
  { label: "HBZ BANK", value: "570137" },
  { label: "FIRST NATIONAL BANK", value: "250655" },
  { label: "OM BANK LIMITED", value: "352000" },
  { label: "ACCESS BANK", value: "410105" },
  { label: "AFRICAN BANK", value: "430000" },
  { label: "HBZ BANK", value: "570145" },
  { label: "AFRICAN BANK INCORP. UBANK", value: "431010" },
  { label: "JP MORGAN CHASE BANK", value: "432000" },
  { label: "CAPITEC BUSINESS", value: "450105" },
  { label: "SOUTH AFRICAN POST OFFICE", value: "460005" },
  { label: "HBZ BANK", value: "570326" },
  { label: "BIDVEST BANK", value: "462005" },
  { label: "CAPITEC BANK LIMITED", value: "470010" },
  { label: "HBZ BANK", value: "570100" },
  { label: "HBZ BANK", value: "570105" },
  { label: "HBZ BANK", value: "570112" },
  { label: "HBZ BANK", value: "570126" },
  { label: "HBZ BANK", value: "570226" },
  { label: "INVESTEC BANK LIMITED", value: "580105" },
  { label: "AFRICAN BANK BUSINESS", value: "584000" },
  { label: "OLYMPUS MOBILE", value: "585001" },
  { label: "HSBC BANK PLC - JOHANNESBURG", value: "587000" },
  { label: "VBS MUTUAL BANK", value: "588000" },
  { label: "FINBOND MUTUAL BANK", value: "589000" },
  { label: "ABSA BANK", value: "632005" },
  { label: "MEEG BANK", value: "634221" },
  { label: "MEEG BANK", value: "634321" },
  { label: "UNIBANK LIMITED", value: "790005" },
  { label: "MEEG BANK", value: "634421" },
  { label: "MEEG BANK", value: "634422" },
  { label: "MEEG BANK", value: "634519" },
  { label: "MEEG BANK", value: "634621" },
  { label: "MEEG BANK", value: "634721" },
  { label: "TYME BANK", value: "678910" },
  { label: "DISCOVERY BANK", value: "679000" },
  { label: "SASFIN BANK", value: "683000" },
  { label: "SASFIN BANK", value: "683001" },
  { label: "STANDARD CHARTERED BANK", value: "730020" },
  { label: "ALBARAKA BANK", value: "800000" },
  { label: "STATE BANK OF INDIA", value: "801000" },
  { label: "BANK ZERO", value: "888000" },
  { label: "RESERVE BANK", value: "900105" },
  { label: "RESERVE BANK", value: "900145" },
  { label: "RESERVE BANK", value: "910145" },
];

/** Sheet: ORG_OWNSP_TYPE  */
export const orgOwnspTypeOptions: SelectOption[] = [
  { label: "COLOURED COMPANIES 100% OWNED", value: "7" },
  { label: "BLACK WOMEN-EMPOWERED COMPANIES > 50% OWNED", value: "1" },
  { label: "BLACK-OWNED ENTITY > 50% OWNED", value: "2" },
  { label: "BLACK EMPOWERED ENTITY 25% TO 50% OWNED", value: "3" },
  { label: "NON BEE", value: "5" },
  { label: "ASIAN COMPANIES 100% OWNED", value: "6" },
  { label: "BLACK INFLUENCED ENTITY 5% TO 25 % OWNED", value: "4" },
  { label: "BLACK COMPANIES 100% OWNED", value: "8" },
  { label: "CHINESE OWNED", value: "9" },
];

/** Sheet: BBBEE_LEVEL */
export const bbbeeLevelOptions: SelectOption[] = [
  { label: "3 - 110% Procurement Recognition", value: "3" },
  { label: "2 - 125% Procurement Recognition", value: "2" },
  { label: "1 - 135% Procurement Recognition", value: "1" },
  { label: "5 - 80% Procurement Recognition", value: "5" },
  { label: "6 - 60% Procurement Recognition", value: "6" },
  { label: "4 - 100% Procurement Recognition", value: "4" },
  { label: "7 - 50% Procurement Recognition", value: "7" },
  { label: "8 - 10% Procurement Recognition", value: "8" },
  { label: "Non compliant - 0% Procurement Recognition", value: "9" },
];

/** Sheet: BBBEE_BFOWN_CL */
export const bbbeeBfownClOptions: SelectOption[] = [
  { label: "No black woman ownership", value: "1" },
  { label: "<30% black woman ownership", value: "2" },
  { label: ">= 30% black woman ownership", value: "3" },
];

/** Sheet: ENT_CLASSIF */
export const entClassifOptions: SelectOption[] = [
  { label: "Financial Institution", value: "FI" },
  { label: "Non-financial Institution", value: "NFI" },
  { label: "Managed Investment Entity", value: "MIE" },
];

/** Sheet: SOURC_OF_FUNDS */
export const sourcOfFundsOptions: SelectOption[] = [
  { label: "Inheritance", value: "1" },
  { label: "Winnings", value: "2" },
  { label: "Legal Settlement", value: "3" },
  { label: "Insurance Payout", value: "6" },
  { label: "Pension Payout", value: "4" },
  { label: "Investment payout", value: "7" },
  { label: "Regular Income", value: "9" },
  { label: "Lump Sum Payout", value: "8" },
  { label: "Gift", value: "5" },
  { label: "Liquidation of Assets", value: "14" },
  { label: "Card Refunds/reversals", value: "12" },
  { label: "Card Cash Backs", value: "13" },
  { label: "Shareholder loans", value: "15" },
  { label: "Card Sales", value: "11" },
  { label: "Allowance", value: "20" },
  { label: "Grant Recipient", value: "19" },
  { label: "Accumulated Savings", value: "23" },
  { label: "Profits from sale of business/property", value: "22" },
  { label: "Maintenance", value: "28" },
  { label: "Bonus", value: "30" },
  { label: "Profit from business activity", value: "10" },
  { label: "Irregular Income", value: "18" },
  { label: "BEE Transaction", value: "16" },
  { label: "Salary / Wage Income", value: "17" },
  { label: "Donation", value: "21" },
  { label: "Board fees", value: "26" },
  { label: "Dividend pay-out", value: "24" },
  { label: "Rental", value: "25" },
  { label: "Director fees", value: "27" },
  { label: "Trust distributions", value: "29" },
  { label: "Interest received", value: "31" },
];

/** Sheet: INSTY */
export const businessIndustryOptions: SelectOption[] = [
  { label: "AGRICULTURE, HUNTING AND FORESTRY", value: "1" },
  { label: "FISHING", value: "2" },
  { label: "MINING AND QUARRYING", value: "3" },
  { label: "MANUFACTURING", value: "4" },
  { label: "ELECTRIC, GAS, STEAM, HOT WATER SUPPLY", value: "5" },
  { label: "CONSTRUCTION", value: "6" },
  { label: "WHOLESALE AND RETAIL TRADE", value: "7" },
  { label: "HOTELS AND RESTAURANTS", value: "8" },
  { label: "TRANSPORT, STORAGE AND COMMUNICATIONS", value: "9" },
  { label: "FINANCIAL INTERMEDIATION", value: "10" },
  { label: "REAL ESTATE, RENTING, BUSSINESS ACT", value: "11" },
  { label: "PUBLIC ADMIN, DEFENCE, COMP SOC SECURITY", value: "12" },
  { label: "EDUCATION", value: "13" },
  { label: "HEALTH AND SOCIAL WORK", value: "14" },
  { label: "OTHER COMM, SOCIAL, PERSONAL SERV ACT", value: "15" },
  { label: "ACT OF PRIV HOUSEHOLDS AS EMPLOYERS", value: "16" },
  { label: "EXTRATERRITORIAL ORG AND BODIES", value: "17" },
  { label: "UNCLASSIFIED", value: "100" },
  { label: "AGRICULT, HUNTING , RLTD SERV ACTVTIES", value: "1000" },
  { label: "GROW OF CROPS; MARKET GARDEN; HORTICULT", value: "1100" },
  { label: "GROWING OF CEREALS, OTHER WINTER CROPS", value: "1110" },
  { label: "DRYLAND GRAINS: MAIZE,WHEAT,SFLOWER, BEANS", value: "1111" },
  { label: "DRYLAND SUGARCANE", value: "1112" },
  { label: "DRYLAND OTHER: COTTON, HAY, TOBACCO, TEA", value: "1113" },
  { label: "IRRIGATED GRAINS: MAIZE,WHEAT,SFLOWER, BEANS", value: "1114" },
  { label: "IRRIGATED SUGARCANE", value: "1115" },
  { label: "IRRIGATED OTHER: COTTON, HAY, TOBACCO, TEA", value: "1116" },
  { label: "PRODUCTION OF CANNABIS(CULTIVATION)", value: "1117" },
  { label: "GROWING OF VEGETABLES, HORTICULT SPECIAL", value: "1120" },
  { label: "VEGETABLES FOR SUPERMARKETS / EXPORTS", value: "1121" },
  { label: "VEGETABLES FOR FRESH PRODUCE MARKETS", value: "1122" },
  { label: "VEGETABLES FOR INFORMAL MARKETS", value: "1123" },
  { label: "VEGETABLES FOR PROCESSING", value: "1124" },
  { label: "PROD: SEED, PLANTING MATERIALS FOR FARMERS", value: "1125" },
  { label: "PROD: SEEDLINGS, SHRUBS FOR GARDEN NURSERIES", value: "1126" },
  { label: "PROD IN GREENHOUSES:VEGETABLES, FLOWERS", value: "1127" },
  { label: "GROW OF FRUIT, NUT, BEVERAGE, SPICE", value: "1130" },
  { label: "CITRUS FARMING", value: "1131" },
  { label: "TABLE GRAPE", value: "1132" },
  { label: "WINE GRAPE", value: "1133" },
  { label: "DECIDUOS FRUIT", value: "1134" },
  { label: "SUBTROPICAL FRUIT", value: "1135" },
  { label: "NUTS:MACADAMIA; PECAN; ALMONDS; WALNUTS", value: "1136" },
  { label: "BLUEBERRY, BLACKBERRY, CRANBERRY, STRAWBERRY", value: "1137" },
  { label: "HERBS AND SPICES", value: "1138" },
  { label: "FARMING OF ANIMALS", value: "1200" },
  { label: "FARMING OF CATTLE, SHEEP, GOATS, HORSES", value: "1210" },
  { label: "EXTENSIVE FARMING OF CATTLE: NATURAL GRAZING", value: "1211" },
  { label: "EXTENSIVE FARMING OF SHEEP,GOATS: NAT GRAZING", value: "1212" },
  { label: "FARMING WITH HORSES, MULES AND HINNIES", value: "1213" },
  { label: "OTHER ANIMAL FARMING, ANIMAL PRODUCTS", value: "1220" },
  { label: "DAIRY FARMING", value: "1222" },
  { label: "FEEDLOTS AND BACK GROUNDING", value: "1223" },
  { label: "OSTRICH FARMING", value: "1224" },
  { label: "PIG FARMING", value: "1225" },
  { label: "BROILER FARMING (CHICKENS)", value: "1226" },
  { label: "EGG FARMING", value: "1227" },
  { label: "GROW CROPS COMBINE WTH FARM OF ANIMLS", value: "1300" },
  { label: "AGRICULTURAL , ANIMAL HUSBNDRY SERV ACTV", value: "1400" },
  { label: "CO-OPERATIVES , PRIMARY INPUT PROVIDERS", value: "1401" },
  { label: "FARMER BODIES, GROWERS ASS, BREEDER SOC", value: "1402" },
  { label: "AGRICULTURE SERVICE ACTIVITIES", value: "1403" },
  { label: "PRODUCTION OF CANNABIS (PROCESSING)", value: "1404" },
  { label: "HUNTING, TRAPPING , GAME PROPAGATION", value: "1500" },
  { label: "GAME PROPAGATION (BREEDING)", value: "1510" },
  { label: "HUNTING AND TRAPPING", value: "1520" },
  { label: "FORESTRY, LOGGING , RLTD SERV ACTVTIES", value: "2000" },
  { label: "FORESTRY AND RELATED SERVICES", value: "2100" },
  { label: "LOGGING AND RELATED SERVICES", value: "2200" },
  { label: "FISHING, AQUACULTURE , SERV ACTV: FISHNG", value: "5000" },
  { label: "FISHING", value: "5010" },
  { label: "FISH HATCHERIES AND FISH FARMS (FRESH WATER)", value: "5020" },
  { label: "CROCODILE", value: "5021" },
  { label: "OCEAN AND COASTAL FISHING (SEA WATER)", value: "5100" },
  { label: "FISH HATCHERIES AND FISH FARMS (FRESH WATER)", value: "5200" },
  { label: "MINING OF COAL, LIGNITE; EXTRACT OF PEAT", value: "10000" },
  { label: "MINING , AGGLOMERATION: HARD COAL", value: "10100" },
  { label: "MINING , AGGLOMERATION: LIGNITE", value: "10200" },
  { label: "EXTRACTION, AGGLOMERATION: PEAT", value: "10300" },
  { label: "EXTRCT CRUDE PETROL,NATURL GAS,SERV ACTV", value: "11000" },
  { label: "EXTRACT OF CRUDE PETROLEUM , NATURL GAS", value: "11100" },
  { label: "SERV ACTVTIES RLTD TO OIL, GAS EXTRACTN", value: "11200" },
  { label: "MINING OF URANIUM , THORIUM ORES", value: "12000" },
  { label: "MINING OF METAL ORES", value: "13000" },
  { label: "MINING OF IRON ORES", value: "13100" },
  { label: "MINING NON-FERROUS METAL,EXCPT URANIUM", value: "13200" },
  { label: "MINING GOLD", value: "13201" },
  { label: "MINING PLATINUM", value: "13202" },
  { label: "MINING SILVER", value: "13203" },
  { label: "MINING ALUMINIUM", value: "13204" },
  { label: "MINING MANGANESE", value: "13205" },
  { label: "MINING FERRO-ALLOY, COBALT, VANADIUM", value: "13206" },
  { label: "MINING OF COPPER", value: "13207" },
  { label: "MINING OF NICKEL", value: "13208" },
  { label: "MINING OF ZINC", value: "13209" },
  { label: "MINING OF LEAD", value: "13210" },
  { label: "MINING OF TIN", value: "13211" },
  { label: "MINING TANTALUM", value: "13212" },
  { label: "OTHER MINING , QUARRYING", value: "14000" },
  { label: "QUARRYING OF STONE, SAND , CLAY", value: "14100" },
  { label: "MINING AND QUARRYING N.E.C.", value: "14200" },
  { label: "MINING OF CHEMICAL , FERTILIZER MINERALS", value: "14210" },
  { label: "EXTRACTION OF SALT", value: "14220" },
  { label: "OTHER MINING AND QUARRYING N.E.C.", value: "14290" },
  { label: "MANUFACT OF FOOD PRODUCTS , BEVERAGES", value: "15000" },
  { label: "PROD PROCESS PRESERV MEAT, FISH, FRUIT", value: "15100" },
  { label: "PRODUCTION, PROCESSING, PRESERVATION OF MEAT", value: "15110" },
  { label: "PROCESSING, PRESERVATION: FISH, FISH PRODUCTS", value: "15120" },
  { label: "PROCESSING, PRESERVATION: FRUIT, VEGETABLES", value: "15130" },
  { label: "MANUFACTURE: VEGETABLE, ANIMAL OILS AND FATS", value: "15140" },
  { label: "MANUFACTURE OF DAIRY PRODUCTS", value: "15200" },
  { label: "MANUF: GRAIN MILL PROD, STARCHES, ANIMAL FEED", value: "15300" },
  { label: "MANUFACTURE OF GRAIN MILL PRODUCTS", value: "15310" },
  { label: "MANUFACTURE OF STARCHES", value: "15320" },
  { label: "MANUFACTURE OF ANIMAL FEEDS", value: "15330" },
  { label: "MANUFACTURE OF OTHER FOOD PRODUCTS", value: "15400" },
  { label: "MANUFACTURE BAKERY PRODUCTS", value: "15410" },
  { label: "MANUFACTURE SUGAR", value: "15420" },
  { label: "MANUFACTURE COCOA", value: "15430" },
  { label: "MANUFACTURE MACARONI", value: "15440" },
  { label: "MANUFACTURE OF PRODUCTS WITH CBD INGREDIENT", value: "15450" },
  { label: "MANUFACTURE OTHER FOOD PRODUCTS", value: "15490" },
  { label: "MANUFACTURE OF BEVERAGES", value: "15500" },
  { label: "DISTILLING AND BLENDING OF SPIRITS", value: "15510" },
  { label: "MANUFACTURE OF WINES", value: "15520" },
  { label: "MANUFACTURE OF MALT LIQUORS", value: "15530" },
  { label: "MANUFACTURE OF SOFT DRINKS; MINERAL WATER", value: "15540" },
  { label: "MANUFACTURING OF TOBACCO PRODUCTS", value: "16000" },
  { label: "MANUFACT OF TEXTILES", value: "17000" },
  { label: "SPINNING, WEAVING AND FINISHING OF TEXTILES", value: "17100" },
  { label: "PREPERATION AND SPINNING OF TEXTILE FIBRES", value: "17110" },
  { label: "FINISHING OF TEXTILES", value: "17120" },
  { label: "MANUFACT OF OTHER TEXTILES", value: "17200" },
  { label: "MANUFACT OF MADE-UP TEXTILE ARTICLES", value: "17210" },
  { label: "MANUFACT OF CARPETS AND RUGS", value: "17220" },
  { label: "MANUFACT CORDAGE,ROPE,TWINE,NETTING", value: "17230" },
  { label: "MANUFACTURE OF COTTON TEXTILES", value: "17240" },
  { label: "MANUFACT OF OTHER TEXTILES N.E.C.", value: "17290" },
  { label: "MANUFACT KNITTED,CROCHETED FABRICS", value: "17300" },
  { label: "MANUFACT CLOTHING, FOOTWEAR , APPAREL", value: "18000" },
  { label: "MANUFACT WEARING APPAREL, EXCEPT FUR", value: "18100" },
  { label: "DRESSING, DYEING FUR, MANUFACT FUR ART", value: "18200" },
  { label: "TANNING , DRESSING OF LEATHER", value: "19000" },
  { label: "TANNING , DRESSING OF LEATHER", value: "19100" },
  { label: "TANNING AND DRESSING OF LEATHER", value: "19110" },
  { label: "MANUFACT LUGGAGE,HANDBAGS,SADDLERY", value: "19120" },
  { label: "MANUFACT OF FOOTWEAR", value: "19200" },
  { label: "MANUFACT WOOD , PAPER PRODUCTS", value: "20000" },
  { label: "SAWMILLING ANF PLANING OF WOOD", value: "20100" },
  { label: "MANUFACT PRODUCTS WOOD,CORK,STRAW", value: "20200" },
  { label: "MANUFACT VENEER, PLYWOOD, LAMINBOARD", value: "20210" },
  { label: "MANUFACT OF BUILD CARPENTRY, JOINERY", value: "20220" },
  { label: "MANUFACT OF WOODEN CONTAINERS", value: "20230" },
  { label: "MANUFACT OTHER WOOD PROD, CORK ARTCL", value: "20290" },
  { label: "MANUFACT OF PAPER AND PAPER PRODUCTS", value: "21000" },
  { label: "MANUFACT OF PULP, PAPER AND PAPERBOARD", value: "21010" },
  { label: "MANUFACT OF CORRUGATED PAPER, PAPERBOARD", value: "21020" },
  { label: "MANUFACT OTHER ARTCLS PAPER, PAPERBOARD", value: "21090" },
  { label: "PUBLISH,PRINT, REPRODUCTION RECORDED MED", value: "22000" },
  { label: "PUBLISHING", value: "22100" },
  { label: "PUBLISH BOOKS,BROCHURES,OTHER PUBLICAT", value: "22110" },
  { label: "PUBLISH NEWSPAPERS, JOURNALS, PERIODICLS", value: "22120" },
  { label: "PUBLISHING OF MUSIC", value: "22130" },
  { label: "OTHER PUBLISHING", value: "22190" },
  { label: "PRINT SERVICE ACTIV RLTD TO PRINTING", value: "22200" },
  { label: "PRINTING", value: "22210" },
  { label: "SERVICE ACTIVITIES RELATED TO PRINTING", value: "22220" },
  { label: "REPRODUCTION OF RECORDED MEDIA", value: "22300" },
  { label: "MANUFACT COKE, REFINED PETROLEUM PROD", value: "23000" },
  { label: "MANUFACT OF COKE OVEN PRODUCTS", value: "23100" },
  { label: "MANUFACT REFINED PETROLEUM PRODUCTS", value: "23200" },
  { label: "PROCESSING OF NUCLEAR FUEL", value: "23300" },
  { label: "MANUFACT CHEMICALS , CHEMICAL PRODUCTS", value: "24000" },
  { label: "MANUFACTURING OF BASIC CHEMICALS", value: "24100" },
  { label: "MANUFACT BASIC CHEMICAL EXCPT FERTILIZER", value: "24110" },
  { label: "MANUFACTURE: FERTILIZERS, NITROGEN COMPOUNDS", value: "24120" },
  { label: "MANUFACT PLASTICS IN PRIMARY FORMS", value: "24130" },
  { label: "MANUFACT OF OTHER CHEMICAL PRODUCTS", value: "24200" },
  { label: "MANUFACT OF PESTICIDES", value: "24210" },
  { label: "MANUFACT PAINTS, VARNISHES, COATINGS", value: "24220" },
  { label: "MANUFACT OF PHARMACEUTICALS", value: "24230" },
  { label: "MANUFACT SOAP, , DETERGENTS", value: "24240" },
  { label: "MANUFACT OTHER CHEMICAL PRODUCTS N.E.C.", value: "24290" },
  { label: "MANUFACT OF MAN-MADE FIBRES", value: "24300" },
  { label: "MANUFACT RUBBER , PLASTIC PRODUCTS", value: "25000" },
  { label: "MANUFACT OF RUBBER PRODUCTS", value: "25100" },
  { label: "MANUFACT RUBBER TYRES, TUBES, RETREAD", value: "25110" },
  { label: "MANUFACT OF OTHER RUBBER PRODUCTS", value: "25190" },
  { label: "MANUFACT OF PLASTICS PRODUCTS", value: "25200" },
  { label: "MANUFACT MINERAL PRODUCTS", value: "26000" },
  { label: "MANUFACT OF GLASS , GLASS PRODUCTS", value: "26100" },
  { label: "MANUFACT NON-METALLIC MINERAL PRDCTS NEC", value: "26900" },
  { label: "MANUFACT NON-STRUCTURAL CERAMIC WARE", value: "26910" },
  { label: "MANUFACT OF REFRACTORY CERAMIC PRODUCTS", value: "26920" },
  { label: "MANUFACT STRUCTURAL NON-REFRACTORY CLAY", value: "26930" },
  { label: "MANUFACT OF CEMENT, LIME AND PLASTER", value: "26940" },
  { label: "MANUFACT ARTICLES OF CONCRETE, CEMENT", value: "26950" },
  { label: "CUTTING, SHAPING AND FINISHING OF STONE", value: "26960" },
  { label: "MANUFACT OTHER NON-METAL MINERAL PRDCTS", value: "26990" },
  { label: "MANUFACT OF BASIC METALS", value: "27000" },
  { label: "MANUFACT OF BASIC IRON AND STEEL", value: "27100" },
  { label: "MANUFACT BASIC PRECIOUS, N-FERROUS MTLS", value: "27200" },
  { label: "CASTING OF METALS", value: "27300" },
  { label: "CASTING OF IRON AND STEEL", value: "27310" },
  { label: "CASTING OF NON-FERROUS METALS", value: "27320" },
  { label: "MANUFACT FABRICATED METAL PRODUCTS", value: "28000" },
  { label: "MANUFACT STRUCT METAL PRODUCTS, TANKS", value: "28100" },
  { label: "MANUFACT OF STRUCTURAL METAL PRODUCTS", value: "28110" },
  { label: "MANUFACT TANKS,RESERVOIRS,METAL CONTAIN", value: "28120" },
  { label: "MANUFACT OF STEAM GENERATORS", value: "28130" },
  { label: "MANUFACT OTHER FABRICATED METAL PRODUCTS", value: "28900" },
  { label: "FORGING, PRESS, STAMP, ROLL-FORMING MET", value: "28910" },
  { label: "TREATMENT AND COATING OF METALS", value: "28920" },
  { label: "MANUFACT CUTLERY,HAND TOOLS,GEN HRDWRE", value: "28930" },
  { label: "MANUFAC OTHER FABRICATD METAL PRDCTS NEC", value: "28990" },
  { label: "MANUFACT OF MACHINERY AND EQUIPMENT", value: "29000" },
  { label: "MANUFACT OF GENERAL-PURPOSE MACHINERY", value: "29100" },
  { label: "MANUFACT ENGINES,TURBINES,EXCPT AIRCRAFT", value: "29110" },
  { label: "MANUFACT PUMPS,COMPRESSORS,TAPS , VALVES", value: "29120" },
  { label: "MANUFACT BEARINGS, GEARS, GEARING", value: "29130" },
  { label: "MANUFACT OVENS, FURNACES, FURN BURNERS", value: "29140" },
  { label: "MANUFACT OF LIFTING AND HANDLING EQUIPM", value: "29150" },
  { label: "MANUFACT OTHER GENERAL-PURPOSE MACHINERY", value: "29190" },
  { label: "MANUFACT OF SPECIAL-PURPOSE MACHINERY", value: "29200" },
  { label: "MANUFACTURE: AGRICULTURAL, FORESTRY MACHINERY", value: "29210" },
  { label: "MANUFACT OF MACHINE TOOLS", value: "29220" },
  { label: "MANUFACT OF MACHINERY FOR METALLURGY", value: "29230" },
  { label: "MANUFACT MACHINERY FOR MINING, QUARRYING", value: "29240" },
  { label: "MANUFACTURE: MACHINERY - FOOD PROCESSING", value: "29250" },
  { label: "MANUFACT MACHINERY FOR TEXTILE, APPAREL", value: "29260" },
  { label: "MANUFACT OF WEAPONS AND AMMUNITION", value: "29270" },
  { label: "MANUFACT OTHER SPECIAL-PURPOSE MACHINERY", value: "29290" },
  { label: "MANUFACT OF DOMESTIC APPLIANCES N.E.C.", value: "29300" },
  { label: "MANUFACT OFFICE,ACCO, COMPUTING MCHNR", value: "30000" },
  { label: "MANUFACT ELEC MACHNRY AND APPARATUS", value: "31000" },
  { label: "MANUFACT ELECTRIC MOTORS, GENERATORS", value: "31100" },
  { label: "MANUFACT OF ELECTRICITY DISTRIBUTION", value: "31200" },
  { label: "MANUFACT OF INSULATED WIRE AND CABLE", value: "31300" },
  { label: "MANUFACT OF ACCUMULATORS, PRIMARY CELLS", value: "31400" },
  { label: "MANUFACT ELECTRIC LAMPS,LIGHTING EQPMNT", value: "31500" },
  { label: "MANUFACT OTHER ELECTRICAL EQUIPMENT NEC", value: "31900" },
  { label: "MANUFACT OF RADIO, TELEVISION", value: "32000" },
  { label: "MANUFACT OF ELECTRONIC VALVES , TUBES", value: "32100" },
  { label: "MANUFACT TELEVISION, RADIO TRANSMITTERS", value: "32200" },
  { label: "MANUFACT TELEVISION , RADIO RECEIVERS", value: "32300" },
  { label: "MANUFACT OF MEDICAL, PRECISION INSTRMNTS", value: "33000" },
  { label: "MANUFACT MEDICAL APPLIANCES", value: "33100" },
  { label: "MANUFACT MEDICAL,  SURGICAL EQUIPMENT", value: "33110" },
  { label: "MANUFACT INSTRUMENTS,MEASURING APPL", value: "33120" },
  { label: "MANUFACT INDUSTRIAL PROCESS CNTRL EQPMNT", value: "33130" },
  { label: "MANUFACT OF OPTICAL INSTRUMENTS", value: "33200" },
  { label: "MANUFACT OF WATCHES AND CLOCKS", value: "33300" },
  { label: "MANUFACT MOTOR VEHICLES, TRAILERS", value: "34000" },
  { label: "MANUFACT OF MOTOR VEHICLES", value: "34100" },
  { label: "MANUFACT BODIES FOR MOTOR VEHICLES", value: "34200" },
  { label: "MANUFACT MOTOR VEHICLE PARTS,ACCESS", value: "34300" },
  { label: "MANUFACT OF OTHER TRANSPORT EQUIPMENT", value: "35000" },
  { label: "BUILDING , REPAIRING OF SHIPS AND BOATS", value: "35100" },
  { label: "BUILDING AND REPAIRING OF SHIPS", value: "35110" },
  { label: "BUILDING, REPAIRING PLEASURE/SPORT BOATS", value: "35120" },
  { label: "MANUFACT RAILWAY, TRAMWAY LOCOMOTIVES", value: "35200" },
  { label: "MANUFACT OF AIRCRAFT AND SPACECRAFT", value: "35300" },
  { label: "MANUFACT OF TRANSPORT EQUIPMENT N.E.C.", value: "35900" },
  { label: "MANUFACT OF MOTORCYCLES", value: "35910" },
  { label: "MANUFACT BICYCLES , INVALID CARRIAGES", value: "35920" },
  { label: "MANUFACT OTHER TRANSPORT EQUIPMENT", value: "35990" },
  { label: "MANUFACT FURNITURE; MANUFACTURING N.E.C.", value: "36000" },
  { label: "MANUFACT OF FURNITURE", value: "36100" },
  { label: "MANUFACTURING N.E.C.", value: "36900" },
  { label: "MANUFACT JEWELLERY , RELATED ARTICLES", value: "36910" },
  { label: "MANUFACT OF MUSICAL INSTRUMENTS", value: "36920" },
  { label: "MANUFACT OF SPORTS GOODS", value: "36930" },
  { label: "MANUFACT OF GAMES AND TOYS", value: "36940" },
  { label: "OTHER MANUFACTURING N.E.C.", value: "36990" },
  { label: "RECYCLING", value: "37000" },
  { label: "RECYCLING METAL WASTE , SCRAP", value: "37100" },
  { label: "RECYCLING NON-METAL WASTE , SCRAP", value: "37200" },
  { label: "ELECTRICTY, GAS, STEAM, HOT WATER SUPPLY", value: "40000" },
  { label: "ELECTRIC,GAS,HOT WATER SUPPLY", value: "40001" },
  { label: "PRODUCTION, TRANSMISSION OF ELECTRICITY", value: "40100" },
  { label: "PRODUCTION,COLLECTION AND DISTRIBUTION OF ELE", value: "40101" },
  { label: "MANUFACT GAS;GASEOUS FUELS DISTRIBUTION", value: "40200" },
  { label: "STEAM AND HOT WATER SUPPLY", value: "40300" },
  { label: "COLLECTION,WATER PURIFICATION, DISTRIB", value: "41000" },
  { label: "CONSTRUCTION", value: "45000" },
  { label: "SITE PREPARATION", value: "45100" },
  { label: "BUILD COMPL CONSTRUCTIONS, PARTS THEREOF", value: "45200" },
  { label: "CIVIL ENGINEERING WORKS", value: "45210" },
  { label: "BUILDING INSTALLATION", value: "45300" },
  { label: "BUILDING COMPLETION", value: "45400" },
  { label: "RENTING CONSTRUCTION,DEMOLITION EQUIPM", value: "45500" },
  { label: "AUTOMOTIVE TRADE , RELATED BUSINESS", value: "50000" },
  { label: "SALE OF MOTOR VEHICLES", value: "50100" },
  { label: "MAINTENANCE , REPAIR OF MOTOR VEHICLES", value: "50200" },
  { label: "SALE OF MOTOR VEHICLE PARTS, ACCESSORIES", value: "50300" },
  { label: "SALE, MAINT, REPAIR OF MOTORCYCLES", value: "50400" },
  { label: "RETAIL SALE OF AUTOMOTIVE FUEL", value: "50500" },
  { label: "WHOLESALE TRADE", value: "51000" },
  { label: "WHOLESALE ON A FEE OR CONTRACT BASIS", value: "51100" },
  { label: "METAL COMMODITY TRADERS", value: "51101" },
  { label: "OTHER COMMODITY TRADERS", value: "51102" },
  { label: "WHOLESALE OF AGRICULTURAL RAW MATERIALS", value: "51200" },
  { label: "WSALE TRADE: AGRIC RAW MATERIALS, ANIMALS", value: "51210" },
  { label: "WHOLESALE FOOD, BEVERAGES , TOBACCO", value: "51220" },
  { label: "DISTRIBUTION OF CANNABIS RELATED PRODUCTS", value: "51230" },
  { label: "WHOLESALE OF HOUSEHOLD GOODS", value: "51300" },
  { label: "WHOLESALE TEXTILES, CLOTHING, FOOTWEAR", value: "51310" },
  { label: "WHOLESALE OF OTHER HOUSEHOLD GOODS", value: "51390" },
  { label: "WHOLESALE NON-AGRIC INTERMEDIATE PRDCT", value: "51400" },
  { label: "WHOLESALE SOLID, LIQUID , GASEOUS FUELS", value: "51410" },
  { label: "WHOLESALE OF METALS AND METAL ORES", value: "51420" },
  { label: "WHOLESALE CONSTRUCT MATERIALS, HARDWARE", value: "51430" },
  { label: "WHOLESALE OTHER INTERMEDIATE PRODUCTS", value: "51490" },
  { label: "WHOLESALE OF MACHINERY,EQUIPMENT, SUPPL", value: "51500" },
  { label: "WHOLESALE OF COMPUTERS , SOFTWARE", value: "51510" },
  { label: "WHOLESALE ELECTRONIC,TELECOMMS PARTS", value: "51520" },
  { label: "WHOLESALE OTHER MACHINERY,EQUIPM, SUPPL", value: "51590" },
  { label: "OTHER WHOLESALE", value: "51900" },
  { label: "RETAIL TRADE", value: "52000" },
  { label: "NON-SPECIALIZED RETAIL TRADE IN STORES", value: "52100" },
  { label: "RETAIL SALE IN NON-SPECIALIZED STORES", value: "52110" },
  { label: "OTHR RETAIL SALE IN NON-SPECIALZD STORES", value: "52190" },
  { label: "RETAIL SALE OF FOOD, BEVERAGES, TOBACCO", value: "52200" },
  { label: "SALE OF CANNABIS AND RELATED PRODUCTS", value: "52210" },
  { label: "OTHR RETAIL TRADE NEW GOODS, SPECIALIZD", value: "52300" },
  { label: "RETAIL SALE PHARMACEUTIC, MEDICAL GOODS", value: "52310" },
  { label: "RETAIL SALE TEXTILES, CLOTHING, FOOTWEAR", value: "52320" },
  { label: "RETAIL SALE HOUSEHOLD APPL, ARTICLES", value: "52330" },
  { label: "RETAIL SALE OF HARDWARE, PAINTS, GLASS", value: "52340" },
  { label: "RETAIL JEWELLERY TRADERS", value: "52350" },
  { label: "OTHER RETAIL SALE IN SPECIALIZED STORES", value: "52390" },
  { label: "RETAIL SALE SECOND-HAND GOODS IN STORES", value: "52400" },
  { label: "RETAIL TRADE NOT IN STORES", value: "52500" },
  { label: "RETAIL SALE VIA MAIL ORDER HOUSES", value: "52510" },
  { label: "RETAIL SALE VIA STALLS AND MARKETS", value: "52520" },
  { label: "OTHER NON-STORE RETAIL SALE", value: "52590" },
  { label: "REPAIR OF PERSONAL AND HOUSEHOLD GOODS", value: "52600" },
  { label: "HOTELS AND RESTAURANTS", value: "55000" },
  { label: "HOTELS, CAMP SITES OTHR SHORT-STAY ACCOM", value: "55100" },
  { label: "RESTAURANTS, BARS AND CANTEENS", value: "55200" },
  { label: "LAND TRANSPORT; TRANSPORT VIA PIPELINES", value: "60000" },
  { label: "TRANSPORT VIA RAILWAYS", value: "60100" },
  { label: "OTHER LAND TRANSPORT", value: "60200" },
  { label: "OTHER SCHEDULED PASSENGER LAND TRANSPORT", value: "60210" },
  { label: "OTHER NON-SCHED PASSENGER LAND TRNSPRT", value: "60220" },
  { label: "FREIGHT TRANSPORT BY ROAD", value: "60230" },
  { label: "OTHER ROAD TRANSPORT", value: "60240" },
  { label: "TRANSPORT VIA PIPELINES", value: "60300" },
  { label: "WATER TRANSPORT", value: "61000" },
  { label: "SEA AND COASTAL WATER TRANSPORT", value: "61100" },
  { label: "INLAND WATER TRANSPORT", value: "61200" },
  { label: "AIR TRANSPORT", value: "62000" },
  { label: "SCHEDULED AIR TRANSPORT", value: "62100" },
  { label: "NON-SCHEDULED AIR TRANSPORT", value: "62200" },
  { label: "SUPPORTING, AUXILIARY TRANSPORT ACT", value: "63000" },
  { label: "CARGO HANDLING", value: "63010" },
  { label: "STORAGE AND WAREHOUSING", value: "63020" },
  { label: "OTHER SUPPORTING TRANSPORT ACTIVITIES", value: "63030" },
  { label: "ACT TRAVEL AGENCIES, TOUR OPERATORS", value: "63040" },
  { label: "ACTIVITIES OF OTHER TRANSPORT AGENCIES", value: "63090" },
  { label: "POST AND TELECOMMUNICATIONS", value: "64000" },
  { label: "POST AND COURIER ACTIVITIES", value: "64100" },
  { label: "NATIONAL POST ACTIVITIES", value: "64110" },
  { label: "COURIER ACTVTIES OTHER THAN POST ACT", value: "64120" },
  { label: "TELECOMMUNICATIONS", value: "64200" },
  { label: "FINANCIAL INTERMEDIATION,EXCPT INSURANCE", value: "65000" },
  { label: "BANKS", value: "65100" },
  { label: "CENTRAL BANKING", value: "65110" },
  { label: "OTHER MONETARY INTERMEDIATION", value: "65190" },
  { label: "COMMERCIAL/RETAIL/SAVINGS,LOAN BANKS", value: "65191" },
  { label: "INVESTMENT/MERCHANT BANKS", value: "65192" },
  { label: "UNIVERSAL BANKS", value: "65193" },
  { label: "CENTRAL BANKS", value: "65194" },
  { label: "GOVERNMENT CREDIT INSTITITUTIONS", value: "65195" },
  { label: "DEDICATED BANKS", value: "65196" },
  { label: "CO-OPERATIVE BANKS", value: "65197" },
  { label: "MULTILATERAL DEVELOPMENT BANKS", value: "65198" },
  { label: "OTHER FINANCIAL INTERMEDIATION", value: "65900" },
  { label: "FINANCIAL LEASING", value: "65910" },
  { label: "OTHER CREDIT GRANTING", value: "65920" },
  { label: "CREDIT UNIONS", value: "65921" },
  { label: "MORTGAGE , HOUSING CREDIT CORPORATIONS", value: "65922" },
  { label: "BANK HOLDING COMPANIES", value: "65923" },
  { label: "SECURITIES DEALERS", value: "65924" },
  { label: "INDIVIDUAL CREDIT CARD ADVANCES", value: "65925" },
  { label: "INDIVIDUAL OTHER BUSINESS PURPOSES", value: "65926" },
  { label: "INDIVIDUAL OTHER PRIVATE PURPOSES", value: "65927" },
  { label: "INDIVIDUAL PURCHASES OTHER", value: "65928" },
  { label: "INDIVIDUAL BRIDGING FINANCE", value: "65929" },
  { label: "CRYPTOCURRENCY AS A STORAGE OF VALUE", value: "65930" },
  { label: "CRYPTOCURRENCY EXCHANGES", value: "65940" },
  { label: "CRYPTOCURRENCY AS A FINANCIAL SERVICE", value: "65950" },
  { label: "MINING OF CRYPTOCURRENCIES", value: "65960" },
  { label: "NFT MARKETPLACES", value: "65970" },
  { label: "OTHER FINANCIAL INTERMEDIATION N.E.C.", value: "65990" },
  { label: "ASSET MANAGERS", value: "65991" },
  { label: "UNIT TRUSTS", value: "65992" },
  { label: "HEDGE FUNDS", value: "65993" },
  { label: "INVESTMENT TRUSTS", value: "65994" },
  { label: "PRIVATE EQUITY FUNDS", value: "65995" },
  { label: "FACTORING/FINANCE/DISCOUNT HOUSES", value: "65996" },
  { label: "NON BANK CREDIT INSTITUTIONS", value: "65997" },
  { label: "MONEY MARKET MUTUAL FUNDS", value: "65998" },
  { label: "OTHER FINANCIAL INTERMEDIARIES", value: "65999" },
  { label: "INSURANCE, PENSION FUNDING", value: "66000" },
  { label: "LIFE INSURANCE", value: "66010" },
  { label: "PENSION FUNDING", value: "66020" },
  { label: "NON LIFE ASSURANCE", value: "66030" },
  { label: "SHORT TERM INSURANCE", value: "66031" },
  { label: "REINSURANCE", value: "66032" },
  { label: "UNIVERSAL INSURANCE", value: "66033" },
  { label: "MEDICAL AID", value: "66034" },
  { label: "ACTVTIES AUXILIARY TO FIN INTERMEDIATION", value: "67000" },
  { label: "FIN INTRMDTION ACTVTIES,EXCPT INSURANCE", value: "67100" },
  { label: "ADMINISTRATION OF FINANCIAL MARKETS", value: "67110" },
  { label: "PLACED BY FUND MANAGERS", value: "67111" },
  { label: "PLACED BY FUND MANGRS:OWNRSHIP UNCERTAIN", value: "67112" },
  { label: "SECURITY DEALING ACTIVITIES", value: "67120" },
  { label: "TRADE FINANCING", value: "67130" },
  { label: "FUTURES BROKERS", value: "67140" },
  { label: "ACTVTIES AUXILIARY, FIN INTRMDTION NEC", value: "67190" },
  { label: "COLLATERALISED LOAN OBLIGATIONS", value: "67191" },
  { label: "COLLATERALISED MORTGAGE OBLIGATIONS", value: "67192" },
  { label: "COLLATERALISED DEBT OBLIGATIONS", value: "67193" },
  { label: "LONG TERM ASSET BACKED VEHICLE", value: "67194" },
  { label: "SHORT TERM ASSET BACKED VEHICLE", value: "67195" },
  { label: "OTHER AUXILLIARY ACTIVITIES", value: "67196" },
  { label: "ACTS AUXILIARY:INSURANCE, PENSION FUNDS", value: "67200" },
  { label: "REAL ESTATE ACTIVITIES", value: "70000" },
  { label: "REAL ESTATE ACTVTIES:OWN/LEASED PROPERTY", value: "70100" },
  { label: "REAL ESTATE ACTVTIES - RESIDENTIAL", value: "70101" },
  { label: "REAL ESTATE ACTVTIES - COMMERCIAL", value: "70102" },
  { label: "REAL ESTATE ACTVTIES - INDUSTRIAL", value: "70103" },
  { label: "REAL ESTATE ACTVTIES - AGRICULTURE", value: "70104" },
  { label: "PROPERTY DEVELOPMENT AND INVESTMENT", value: "70110" },
  { label: "PROPERTY DEVELOPMENT - INDUSTRIAL", value: "70111" },
  { label: "PROPERTY DEVELOPMENT - RESIDENTIAL", value: "70112" },
  { label: "PROPERTY DEVELOPMENT - COMMERCIAL", value: "70113" },
  { label: "PROPERTY DEVELOPMENT - OTHER", value: "70114" },
  { label: "REAL ESTATE INVESTMENT TRUSTS", value: "70120" },
  { label: "PROPERTY INVESTMENT - INDUSTRIAL", value: "70121" },
  { label: "PROPERTY INVESTMENT - RESIDENTIAL", value: "70122" },
  { label: "PROPERTY INVESTMENT - COMMERCIAL", value: "70123" },
  { label: "PROPERTY INVESTMENT - OTHER", value: "70124" },
  { label: "REAL EST ACTIVITIES: FEE/CONTRACT BASIS", value: "70200" },
  { label: "RENT MACHINRY, EQUIPM WITH NO OPERATOR", value: "71000" },
  { label: "RENTING OF TRANSPORT EQUIPMENT", value: "71100" },
  { label: "RENTING OF LAND TRANSPORT EQUIPMENT", value: "71110" },
  { label: "RENTING OF WATER TRANSPORT EQUIPMENT", value: "71120" },
  { label: "RENTING OF AIR TRANSPORT EQUIPMENT", value: "71130" },
  { label: "RENTING OF OTHER MACHINERY , EQUIPMENT", value: "71200" },
  { label: "RENTING: AGRIC MACHINERY AND EQUIPMENT", value: "71210" },
  { label: "RENTNG CONSTRCTION,CIVIL ENGIN MACHNRY", value: "71220" },
  { label: "RENTING OFFICE MACHINRY, EQUIPMENT", value: "71230" },
  { label: "RENTING OTHER MACHINERY, EQUIPM N.E.C.", value: "71290" },
  { label: "RENTING PERSONAL, HOUSEHOLD GOODS N.E.C.", value: "71300" },
  { label: "COMPUTER AND RELATED ACTIVITIES", value: "72000" },
  { label: "HARDWARE CONSULTANCY", value: "72100" },
  { label: "SOFTWARE PUBLISHING, CONSULT, SUPPLY", value: "72200" },
  { label: "SOFTWARE PUBLISHING", value: "72210" },
  { label: "OTHER SOFTWARE CONSULTANCY , SUPPLY", value: "72290" },
  { label: "DATA PROCESSING", value: "72300" },
  { label: "DATABASE ACTIVITIES", value: "72400" },
  { label: "MAINTENANCE, REPAIR OF OFFICE MACHINERY", value: "72500" },
  { label: "OTHER COMPUTER-RELATED ACTIVITIES", value: "72900" },
  { label: "RESEARCH AND DEVELOPMENT", value: "73000" },
  { label: "RESEARCH, DEV ON NATURAL SCIENCES", value: "73100" },
  { label: "AGRICULTURAL AND LIVESTOCK RESEARCH", value: "73120" },
  { label: "RESEARCH, DEVELOPMENT ON SOCIAL SCIENCES", value: "73200" },
  { label: "OTHER BUSINESS ACTIVITIES", value: "74000" },
  { label: "LEGAL, ACCOUNTNG, BOOKKEEPING, AUDITING", value: "74100" },
  { label: "LEGAL ACTIVITIES", value: "74110" },
  { label: "ACCOUNTING, BOOKKEEPING, AUDITING, TAX", value: "74120" },
  { label: "MARKET RESEARCH , PUBLIC OPINION POLLING", value: "74130" },
  { label: "BUSINESS, MANAGEMT CONSULTANCY ACTVTIES", value: "74140" },
  { label: "ARCHITECT,ENGINEERING,TECHNICAL ACTVTIES", value: "74200" },
  { label: "ARCHITECT,ENGINEERING,RELATED TECHINCAL", value: "74210" },
  { label: "TECHNICAL TESTING AND ANALYSIS", value: "74220" },
  { label: "ADVERTISING", value: "74300" },
  { label: "BUSINESS ACTIVITIES N.E.C.", value: "74900" },
  { label: "LABOUR RECRUITM, PROVISION OF PERSONNEL", value: "74910" },
  { label: "INVESTIGATION AND SECURITY ACTIVITIES", value: "74920" },
  { label: "BUILDING-CLEANING,INDUSTRIAL-CLEANING", value: "74930" },
  { label: "PHOTOGRAPHIC ACTIVITIES", value: "74940" },
  { label: "PACKAGING ACTIVITIES", value: "74950" },
  { label: "OTHER BUSINESS ACTIVITIES N.E.C.", value: "74990" },
  { label: "PUBLIC ADMINISTRATION AND DEFENCE", value: "75000" },
  { label: "STATE, SOCIO-ECON POLICY OF THE COMM", value: "75100" },
  { label: "GOVERNMENT", value: "75110" },
  { label: "PROVINCIAL GOVERNMENT", value: "75111" },
  { label: "LOCAL GOVERNMENT (MUNICIPALTIES)", value: "75112" },
  { label: "CENTRAL GOVERNMENT", value: "75113" },
  { label: "REGULATING ACTV - HEALTH CARE AGENCIES", value: "75120" },
  { label: "REGULATION EFFICIENT BUSINESS OPERATIONS", value: "75130" },
  { label: "SUPPORTING SERVICE ACTVTIES FOR GOVERNM", value: "75140" },
  { label: "PROVISION OF SERVICES TO THE COMMUNITY", value: "75200" },
  { label: "FOREIGN AFFAIRS", value: "75210" },
  { label: "DEFENCE ACTIVITIES", value: "75220" },
  { label: "PUBLIC ORDER AND SAFETY ACTIVITIES", value: "75230" },
  { label: "COMPULSORY SOCIAL SECURITY ACTIVITIES", value: "75300" },
  { label: "EDUCATION", value: "80000" },
  { label: "PRIMARY EDUCATION", value: "80100" },
  { label: "SECONDARY EDUCATION", value: "80200" },
  { label: "GENERAL SECONDARY EDUCATION", value: "80210" },
  { label: "TECHNICAL, VOCATIONAL SECONDARY EDUCAT", value: "80220" },
  { label: "HIGHER EDUCATION", value: "80300" },
  { label: "FURTHER EDUCATION AND TRAINING (FET)", value: "80301" },
  { label: "OTHER EDUCATION & ASSOCIATED SERVICES", value: "80900" },
  { label: "ADULT EDUCATION", value: "80901" },
  { label: "SPECIAL NEEDS EDUCATION", value: "80902" },
  { label: "AFTER-SCHOOL CENTRES", value: "80903" },
  { label: "EARLY CHILDHOOD DEVELOPMENT", value: "80904" },
  { label: "STUDENT BURSARY SCHEMES / ACCOUNTS", value: "80905" },
  { label: "FEEDING / NUTRITION SCHEMES", value: "80906" },
  { label: "EDUCATIONAL SERVICE PROVIDERS", value: "80907" },
  { label: "EDUCATIONAL ASSOCIATIONS", value: "80908" },
  { label: "HEALTH AND SOCIAL WORK", value: "85000" },
  { label: "HUMAN HEALTH ACTIVITIES", value: "85100" },
  { label: "HOSPITAL ACTIVITIES", value: "85110" },
  { label: "MEDICAL AND DENTAL PRACTICE ACTIVITIES", value: "85120" },
  { label: "OTHER HUMAN HEALTH ACTIVITIES", value: "85190" },
  { label: "VETERINARY ACTIVITIES", value: "85200" },
  { label: "SOCIAL WORK ACTIVITIES", value: "85300" },
  { label: "SOCIAL WORK ACTIVT WITH ACCOMMODATION", value: "85310" },
  { label: "SOCIAL WORK ACTIV WITHOUT ACCOMMODATION", value: "85320" },
  { label: "SEWAGE, REFUSE DISPOSAL, SANITATION", value: "90000" },
  { label: "ACTIVITIES OF MEMBERSHIP ORGANIZATIONS", value: "91000" },
  { label: "ACTIVITIES OF BUSINESS, PROF EMPLOYERS", value: "91100" },
  { label: "ACTIVITIES OF BUSINESS, EMPLOYERS ORG", value: "91110" },
  { label: "ACTIVITIES OF PROFESSIONAL ORGANIZATIONS", value: "91120" },
  { label: "ACTIVITIES OF TRADE UNIONS", value: "91200" },
  { label: "ACTIVITIES OF OTHER MEMBERSHIP ORG", value: "91900" },
  { label: "ACTIVITIES OF RELIGIOUS ORGANIZATIONS", value: "91910" },
  { label: "ACTIVITIES OF POLITICAL ORGANIZATIONS", value: "91920" },
  { label: "ACTIVITIES OF OTHER MEMBERSHIP ORG", value: "91990" },
  { label: "RECREATIONAL, CULTURAL , SPORTING ACTV", value: "92000" },
  { label: "MOTION PICTURE, RADIO, TELEVISION", value: "92100" },
  { label: "MOTION PICTURE,VIDEO PRODUCTION,DISTRIB", value: "92110" },
  { label: "MOTION PICTURE PROJECTION", value: "92120" },
  { label: "RADIO AND TELEVISION ACTIVITIES", value: "92130" },
  { label: "DRAMATIC ARTS, MUSIC, OTHER ARTS ACTIV", value: "92140" },
  { label: "OTHER ENTERTAINMENT ACTIVITIES N.E.C.", value: "92190" },
  { label: "NEWS AGENCY ACTIVITIES", value: "92200" },
  { label: "LIBRARY,ARCHIVES,MUSEUMS,CULTURAL ACTV", value: "92300" },
  { label: "LIBRARY AND ARCHIVES ACTIVITIES", value: "92310" },
  { label: "MUSEUMS ACTIVITIES,HISTORIC SITE PRESERV", value: "92320" },
  { label: "BOTANY, ZOOLOGICAL GARDENS,NATURE RESERV", value: "92330" },
  { label: "SPORTING , OTHER RECREATIONAL ACTIVITIES", value: "92400" },
  { label: "SPORTING ACTIVITIES", value: "92410" },
  { label: "ADULT AND PORNOGRAPHIC GOODS AND STORES", value: "92420" },
  { label: "GENTLEMANS ESTATES AND BROTHELS", value: "92430" },
  { label: "ESCORT AGENCIES", value: "92440" },
  { label: "OTHER RECREATIONAL ACTIVITIES", value: "92490" },
  { label: "OTHER SERVICE ACTIVITIES", value: "93000" },
  { label: "WASHING,(DRY)CLEANING TEXTILE,FUR PROD", value: "93010" },
  { label: "HAIRDRESSING , OTHER BEAUTY TREATMENT", value: "93020" },
  { label: "FUNERAL AND RELATED ACTIVITIES", value: "93030" },
  { label: "OTHER SERVICE ACTIVITIES N.E.C.", value: "93090" },
  { label: "PRVT HOUSEHOLDS,DOMESTIC STAFF EMPLOYERS", value: "95000" },
  { label: "GOODS-PRODUCING ACTV OF PRVT HOUSEHOLD", value: "96000" },
  { label: "SERVICE-PRODUCING ACTV OF PRVT HOUSEHOLD", value: "97000" },
  { label: "EXTRATERRITORIAL ORG AND BODIES", value: "99000" },
  { label: "PROVISION OF SERVICES TO THE COMMUNITY", value: "842" },
  { label: "PUBLIC ORDER AND SAFETY ACTIVITIES", value: "8423" },
  { label: "PUBLIC ADMINISTRATION AND DEFENCE", value: "84" },
];

/** Sheet: Province */
export const provinceOptions: SelectOption[] = [
  { label: "FREE STATE", value: "ZAF.FS" },
  { label: "GAUTENG", value: "ZAF.GP" },
  { label: "EASTERN CAPE", value: "ZAF.EC" },
  { label: "KWAZULU NATAL", value: "ZAF.KZN" },
  { label: "LIMPOPO", value: "ZAF.LP" },
  { label: "MPUMALANGA", value: "ZAF.MP" },
  { label: "NORTHERN CAPE", value: "ZAF.NC" },
  { label: "NORTH WEST", value: "ZAF.NW" },
  { label: "WESTERN CAPE", value: "ZAF.WC" },
];

/** Sheet: Country */
export const countryOptions: SelectOption[] = [
  { label: "NEW ZEALAND", value: "NZ" },
  { label: "CURACAO", value: "CW" },
  { label: "UNITED ARAB EMIRATES", value: "AE" },
  { label: "GREECE", value: "GR" },
  { label: "KENYA", value: "KE" },
  { label: "LESOTHO", value: "LS" },
  { label: "VANUATU", value: "VU" },
  { label: "VIRGIN ISLANDS (U.S)", value: "VI" },
  { label: "NAURU", value: "NR" },
  { label: "IRELAND, REPUBLIC OF", value: "IE" },
  { label: "HUNGARY", value: "HU" },
  { label: "ANDORRA", value: "AD" },
  { label: "CENTRAL AFRICAN REPUBLIC", value: "CF" },
  { label: "GUAM", value: "GU" },
  { label: "PHILIPPINES", value: "PH" },
  { label: "AUSTRALIA", value: "AU" },
  { label: "BULGARIA", value: "BG" },
  { label: "BARBADOS", value: "BB" },
  { label: "JORDAN", value: "JO" },
  { label: "BOUVET ISLAND", value: "BV" },
  { label: "CZECH REPUBLIC", value: "CZ" },
  { label: "GHANA", value: "GH" },
  { label: "NETHERLANDS", value: "NL" },
  { label: "DJIBOUTI", value: "DJ" },
  { label: "CANADA", value: "CA" },
  { label: "INDONESIA", value: "ID" },
  { label: "MAURITIUS", value: "MU" },
  { label: "NORWAY", value: "NO" },
  { label: "ALGERIA", value: "DZ" },
  { label: "ITALY", value: "IT" },
  { label: "PAPUA NEW GUINEA", value: "PG" },
  { label: "MACEDONIA,THE FORMER YUGOSLAV REPUBLIC OF", value: "MK" },
  { label: "OMAN", value: "OM" },
  { label: "COLUMBIA", value: "CO" },
  { label: "DENMARK", value: "DK" },
  { label: "HAITI", value: "HT" },
  { label: "CHILE", value: "CL" },
  { label: "THAILAND", value: "TH" },
  { label: "BRITISH INDIAN OCEAN TERRITORY", value: "IO" },
  { label: "NETHERLANDS ANTILLES", value: "AN" },
  { label: "SINGAPORE", value: "SG" },
  { label: "NORTHERN MARIANA ISLANDS", value: "MP" },
  { label: "ALAND ISLAND", value: "AX" },
  { label: "TOKELAU", value: "TK" },
  { label: "ROMANIA", value: "RO" },
  { label: "SIERRA LEONE", value: "SL" },
  { label: "VENEZUELA", value: "VE" },
  { label: "GERMANY", value: "DE" },
  { label: "TURKS & CAICOS ISLANDS", value: "TC" },
  { label: "SINT MAARTEN (DUTCH PART)", value: "SX" },
  { label: "GUYANA", value: "GY" },
  { label: "ANTARCTICA", value: "AQ" },
  { label: "RWANDA", value: "RW" },
  { label: "BANGLADESH", value: "BD" },
  { label: "MAURITANIA", value: "MR" },
  { label: "UNITED STATES MINOR OUTLYING ISLANDS", value: "UM" },
  { label: "BAHRAIN", value: "BH" },
  { label: "COCOS (KEELING) ISLANDS", value: "CC" },
  { label: "GUINEA-BISSAU", value: "GW" },
  { label: "PORTUGAL", value: "PT" },
  { label: "FAEROE ISLANDS", value: "FO" },
  { label: "ZAMBIA", value: "ZM" },
  { label: "MALI", value: "ML" },
  { label: "DOMINICAN REPUBLIC", value: "DO" },
  { label: "COUNTRY UNKNOWN", value: "ZZ" },
  { label: "MALTA", value: "MT" },
  { label: "SAINT LUCIA", value: "LC" },
  { label: "MACAU", value: "MO" },
  { label: "PALESTINIAN TERRITORY, OCCUPIED", value: "PS" },
  { label: "SAINT HELENA", value: "SH" },
  { label: "YEMEN", value: "YE" },
  { label: "CHRISTMAS ISLAND", value: "CX" },
  { label: "PERU", value: "PE" },
  { label: "BOLIVIA", value: "BO" },
  { label: "TIMOR LESTE", value: "TL" },
  { label: "ALBANIA", value: "AL" },
  { label: "QATAR", value: "QA" },
  { label: "LIBERIA", value: "LR" },
  { label: "CYPRUS", value: "CY" },
  { label: "HEARD ISLAND AND MC DONALD ISLANDS", value: "HM" },
  { label: "JAPAN", value: "JP" },
  { label: "SWITZERLAND", value: "CH" },
  { label: "BELIZE", value: "BZ" },
  { label: "MADAGASCAR", value: "MG" },
  { label: "LIBYAN ARAB JAMAHIRIYA", value: "LY" },
  { label: "BAHAMAS", value: "BS" },
  { label: "SAMOA", value: "WS" },
  { label: "UNITED STATES", value: "US" },
  { label: "GABON", value: "GA" },
  { label: "CABO VERDE (CAPE VERDE)", value: "CV" },
  { label: "JAMAICA", value: "JM" },
  { label: "ARGENTINA", value: "AR" },
  { label: "PUERTO RICO", value: "PR" },
  { label: "SVALBARD & JAN MAYEN", value: "SJ" },
  { label: "SOUTH SUDAN", value: "SS" },
  { label: "SLOVENIA", value: "SI" },
  { label: "VIET NAM", value: "VN" },
  { label: "IRAN (ISLAMIC REPUBLIC OF)", value: "IR" },
  { label: "MICRONESIA (FEDERATED STATES OF)", value: "FM" },
  { label: "MARSHALL ISLANDS", value: "MH" },
  { label: "AFGHANISTAN", value: "AF" },
  { label: "MONACO", value: "MC" },
  { label: "CUBA", value: "CU" },
  { label: "SEYCHELLES", value: "SC" },
  { label: "NORFOLK ISLAND", value: "NF" },
  { label: "BURKINA FASO", value: "BF" },
  { label: "KOREA DEMOCRATIC PEOPLE'S REPUBLIC OF", value: "KP" },
  { label: "SRI LANKA", value: "LK" },
  { label: "EAST TIMOR", value: "TP" },
  { label: "KIRIBATI", value: "KI" },
  { label: "SENEGAL", value: "SN" },
  { label: "FRENCH SOUTHERN TERRITORIES", value: "TF" },
  { label: "LIECHTENSTEIN", value: "LI" },
  { label: "RUSSIAN FEDERATION", value: "RU" },
  { label: "ICELAND", value: "IS" },
  { label: "AMERICAN SAMOA", value: "AS" },
  { label: "GRENADA", value: "GD" },
  { label: "SUDAN", value: "SD" },
  { label: "UGANDA", value: "UG" },
  { label: "ZIMBABWE", value: "ZW" },
  { label: "PAKISTAN", value: "PK" },
  { label: "SAUDI ARABIA", value: "SA" },
  { label: "GREENLAND", value: "GL" },
  { label: "FALKLANDS ISLANDS (MALVINAS)", value: "FK" },
  { label: "SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS", value: "GS" },
  { label: "MONTSERRAT", value: "MS" },
  { label: "MEXICO", value: "MX" },
  { label: "HOLY SEE (VATICAN CITY STATE)", value: "VA" },
  { label: "ANTIGUA AND BARBUDA", value: "AG" },
  { label: "BELGIUM", value: "BE" },
  { label: "COTE D'IVOIRE", value: "CI" },
  { label: "EQUATORIAL GUINEA", value: "GQ" },
  { label: "MAYOTTE", value: "YT" },
  { label: "SYRIAN ARAB REPUBLIC", value: "SY" },
  { label: "TURKMENISTAN", value: "TM" },
  { label: "SERBIA", value: "RS" },
  { label: "BELARUS", value: "BY" },
  { label: "SLOVAKIA", value: "SK" },
  { label: "ARUBA", value: "AW" },
  { label: "FRENCH POLYNESIA", value: "PF" },
  { label: "PITCAIRN", value: "PN" },
  { label: "CROATIA", value: "HR" },
  { label: "SWEDEN", value: "SE" },
  { label: "BENIN", value: "BJ" },
  { label: "MOZAMBIQUE", value: "MZ" },
  { label: "NICARAGUA", value: "NI" },
  { label: "TURKISH REP", value: "TY" },
  { label: "FIJI", value: "FJ" },
  { label: "GUATEMALA", value: "GT" },
  { label: "SAINT PIERRE & MIQUELON", value: "PM" },
  { label: "BHUTAN", value: "BT" },
  { label: "DOMINICA", value: "DM" },
  { label: "BERMUDA", value: "BM" },
  { label: "ISRAEL", value: "IL" },
  { label: "LEBANON", value: "LB" },
  { label: "ETHIOPIA", value: "ET" },
  { label: "SURINAME", value: "SR" },
  { label: "PALAU", value: "PW" },
  { label: "BOTSWANA", value: "BW" },
  { label: "KUWAIT", value: "KW" },
  { label: "ANGUILLA", value: "AI" },
  { label: "GAMBIA", value: "GM" },
  { label: "ARMENIA", value: "AM" },
  { label: "GIBRALTAR", value: "GI" },
  { label: "KOSOVO", value: "XK" },
  { label: "ANGOLA", value: "AO" },
  { label: "AUSTRIA", value: "AT" },
  { label: "AZERBAIJAN", value: "AZ" },
  { label: "PARAGUAY", value: "PY" },
  { label: "UZBEKISTAN", value: "UZ" },
  { label: "BOSNIA AND HERZEGOVINA", value: "BA" },
  { label: "BURUNDI", value: "BI" },
  { label: "BRUNEI DARUSSALAM", value: "BN" },
  { label: "BRAZIL", value: "BR" },
  { label: "CONGO, THE DEMOCRATIC REPUBLIC OF THE CONGO", value: "CD" },
  { label: "COSTA RICA", value: "CR" },
  { label: "LAO PEOPLE'S DEMOCRATIC REPUBLIC", value: "LA" },
  { label: "CONGO", value: "CG" },
  { label: "SOLOMON ISLANDS", value: "SB" },
  { label: "COOK ISLANDS", value: "CK" },
  { label: "CAMEROON", value: "CM" },
  { label: "CHINA", value: "CN" },
  { label: "ECUADOR", value: "EC" },
  { label: "INDIA", value: "IN" },
  { label: "REUNION", value: "RE" },
  { label: "ESTONIA", value: "EE" },
  { label: "FRANCE", value: "FR" },
  { label: "EGYPT", value: "EG" },
  { label: "WESTERN SAHARA", value: "EH" },
  { label: "SAINT BARTHELEMY", value: "BL" },
  { label: "ERITREA", value: "ER" },
  { label: "SPAIN", value: "ES" },
  { label: "FINLAND", value: "FI" },
  { label: "UNITED KINGDOM", value: "GB" },
  { label: "TONGA", value: "TO" },
  { label: "GEORGIA", value: "GE" },
  { label: "MONGOLIA", value: "MN" },
  { label: "FRENCH GUIANA", value: "GF" },
  { label: "GUERNSEY", value: "GG" },
  { label: "SAINT KITTS & NEVIS", value: "KN" },
  { label: "GUINEA", value: "GN" },
  { label: "HONDURAS", value: "HN" },
  { label: "GUADELOUPE", value: "GP" },
  { label: "UKRAINE", value: "UA" },
  { label: "HONG KONG", value: "HK" },
  { label: "ISLE OF MAN", value: "IM" },
  { label: "IRAQ", value: "IQ" },
  { label: "NAMIBIA", value: "NA" },
  { label: "JERSEY", value: "JE" },
  { label: "KYRGYZSTAN", value: "KG" },
  { label: "COMOROS", value: "KM" },
  { label: "CAMBODIA", value: "KH" },
  { label: "CAYMAN ISLANDS", value: "KY" },
  { label: "KAZAKSTAN", value: "KZ" },
  { label: "TOGO", value: "TG" },
  { label: "KOREA, REPUBLIC OF", value: "KR" },
  { label: "LITHUANIA", value: "LT" },
  { label: "LUXEMBOURG", value: "LU" },
  { label: "LATVIA", value: "LV" },
  { label: "MOROCCO", value: "MA" },
  { label: "MOLDOVA, REPUBLIC OF", value: "MD" },
  { label: "POLAND", value: "PL" },
  { label: "MONTENEGRO", value: "ME" },
  { label: "MYANMAR", value: "MM" },
  { label: "MARTINIQUE", value: "MQ" },
  { label: "MALDIVES", value: "MV" },
  { label: "MALAWI", value: "MW" },
  { label: "MALAYSIA", value: "MY" },
  { label: "NEW CALEDONIA", value: "NC" },
  { label: "NIGER", value: "NE" },
  { label: "NIGERIA", value: "NG" },
  { label: "NIUE", value: "NU" },
  { label: "SAO TOME & PRINCIPE", value: "ST" },
  { label: "NEPAL", value: "NP" },
  { label: "PANAMA", value: "PA" },
  { label: "SAN MARINO", value: "SM" },
  { label: "SOMALIA", value: "SO" },
  { label: "YUGOSLAVIA", value: "YU" },
  { label: "EL SALVADOR", value: "SV" },
  { label: "ESWATINI", value: "SZ" },
  { label: "CHAD", value: "TD" },
  { label: "SOUTH AFRICA", value: "ZA" },
  { label: "TAJIKISTAN", value: "TJ" },
  { label: "TUNISIA", value: "TN" },
  { label: "TURKEY", value: "TR" },
  { label: "TRINIDAD & TOBAGO", value: "TT" },
  { label: "TUVALU", value: "TV" },
  { label: "TAIWAN,PROVINCE OF CHINA", value: "TW" },
  { label: "TANZANIA,UNITED REPUBLIC OF", value: "TZ" },
  { label: "URUGUAY", value: "UY" },
  { label: "SAINT VINCENT & THE GRENADINES", value: "VC" },
  { label: "VIRGIN ISLANDS (BRITISH)", value: "VG" },
  { label: "WALLIS & FUTUNA ISLANDS", value: "WF" },
  { label: "BONAIRE, SINT EUSTATIUS AND SABA", value: "BQ" },
  { label: "SAINT MARTIN (FRENCH PART)", value: "MF" },
];

/** Sheet: PMIFP_RLTNP */
export const pmifpRltnpOptions: SelectOption[] = [
  { label: "Son\\Daughter", value: "2" },
  { label: "Business Partner", value: "5" },
  { label: "Sibling", value: "4" },
  { label: "Close Associate", value: "6" },
  { label: "Spouse\\Partner", value: "1" },
  { label: "Parent", value: "3" },
];

/** Sheet: TAX_TYPE */
export const taxTypeOptions: SelectOption[] = [
  { label: "ARGENTINA: INCOME TAX", value: "AR2" },
  { label: "CHINA: INCOME TAX", value: "CN3" },
  { label: "COLOMBIA: INCOME TAX", value: "CO3" },
  { label: "BOTSWANA : VAT", value: "BW1" },
  { label: "GERMANY: VAT", value: "DE0" },
  { label: "Cuba : Income Tax Number", value: "CU1" },
  { label: "BRAZIL: INCOME TAX (STATE TAX)", value: "BR3" },
  { label: "GERMANY: INCOME TAX", value: "GE4" },
  { label: "DENMARK: VAT", value: "DK0" },
  { label: "Slovenia: VAT Registration Number", value: "SI0" },
  { label: "BOTSWANA: INCOME TAX", value: "BW3" },
  { label: "DENMARK: INCOME TAX", value: "DK2" },
  { label: "UNITED KINGDOM: VAT", value: "GB0" },
  { label: "FINLAND: VAT", value: "FI0" },
  { label: "INDONESIA: INCOME TAX (NPWP)", value: "ID1" },
  { label: "FRANCE: VAT", value: "FR0" },
  { label: "INDONESIA: VAT (NPPKP)", value: "ID3" },
  { label: "Armenia : VAT Number", value: "AM2" },
  { label: "UNITED KINGDOM:INCOME TAX NATIONAL INS", value: "GB2" },
  { label: "IRELAND: VAT", value: "IE0" },
  { label: "Niger : VAT Number", value: "NE2" },
  { label: "INDIA: INCOME TAX", value: "IN3" },
  { label: "HONG KONG: VAT", value: "HK1" },
  { label: "ITALY: INCOME TAX (CODICE FISCALE)", value: "IT1" },
  { label: "Honduras : VAT Number", value: "HN2" },
  { label: "SOUTH KOREA: INCOME TAX", value: "KR1" },
  { label: "Costa rica : VAT Number", value: "CR2" },
  { label: "Guernsey, c.i. : Income Tax Number", value: "GG1" },
  { label: "ITALY: VAT (IVA)", value: "IT2" },
  { label: "CAYMAN ISLANDS: VAT", value: "KY1" },
  { label: "CAYMAN ISLANDS: INCOME TAX", value: "KY3" },
  { label: "Bolivia : Income Tax Number", value: "BO1" },
  { label: "Ethiopia : Income Tax Number", value: "ET1" },
  { label: "Guatemala : Income Tax Number", value: "GT1" },
  { label: "LESOTHO: VAT", value: "LS1" },
  { label: "SOUTH KOREA: VAT", value: "KR2" },
  { label: "Brunei darussalam : VAT Number", value: "BN2" },
  { label: "Saint vincent and grenadines: VAT Number", value: "VC2" },
  { label: "LATVIA: INCOME TAX", value: "LV3" },
  { label: "LESOTHO: INCOME TAX", value: "LS3" },
  { label: "Kenya : VAT Number", value: "KE2" },
  { label: "MAURITIUS: INCOME TAX", value: "MU3" },
  { label: "MOZAMBIQUE: VAT", value: "MZ1" },
  { label: "MOZAMBIQUE: INCOME TAX", value: "MZ3" },
  { label: "NAMIBIA: VAT", value: "NA1" },
  { label: "ROMANIA: INCOME TAX", value: "RO1" },
  { label: "NAMIBIA: INCOME TAX", value: "NA3" },
  { label: "RUSSIA: VAT (INN)", value: "RU1" },
  { label: "RUSSIA: INCOME TAX (KPP)", value: "RU3" },
  { label: "SWAZILAND: VAT", value: "SZ1" },
  { label: "Guinea : VAT Number", value: "GN2" },
  { label: "SWAZILAND: INCOME TAX", value: "SZ3" },
  { label: "TAIWAN: VAT (GUI)", value: "TW1" },
  { label: "TAIWAN: INCOME TAX", value: "TW2" },
  { label: "TANZANIA: INCOME TAX", value: "TZ3" },
  { label: "Gabon : VAT Number", value: "GA2" },
  { label: "TANZANIA: VAT", value: "TZ1" },
  { label: "Belize : VAT Number", value: "BZ2" },
  { label: "Isle of man : Income Tax Number", value: "IM1" },
  { label: "UGANDA: INCOME TAX", value: "UG3" },
  { label: "USA INCOME: TAX (EMPLOYER ID)", value: "US2" },
  { label: "USA: VAT (SOCIAL SECURITY)", value: "US1" },
  { label: "VIRGIN ISLANDS (BRITISH): INCOME TAX", value: "VG3" },
  { label: "SOUTH AFRICA: VAT", value: "ZA1" },
  { label: "SOUTH AFRICA: INCOME TAX", value: "ZA3" },
  { label: "YEMEN: INCOME TAX", value: "YE3" },
  { label: "ZAMBIA: VAT", value: "ZM1" },
  { label: "Nigeria : VAT Number", value: "NG2" },
  { label: "ZAMBIA: INCOME TAX", value: "ZM3" },
  { label: "Czech Republic: DIC Number", value: "CZ1" },
  { label: "Philippines: Taxpayer ID Number", value: "PH1" },
  { label: "Netherlands: VAT Registration Number", value: "NL0" },
  { label: "Andorra : Income Tax Number", value: "AD1" },
  { label: "Canada : VAT Number", value: "CA2" },
  { label: "Andorra : VAT Number", value: "AD2" },
  { label: "Austria: Income Tax Number", value: "AT1" },
  { label: "United Arab Emirated : Inc Tax Number", value: "AE1" },
  { label: "United Arab Emirated : VAT Number", value: "AE2" },
  { label: "Afghanistan : Income Tax Number", value: "AF1" },
  { label: "Afghanistan : VAT Number", value: "AF2" },
  { label: "Antigua and barbuda :  Inc Tax Number", value: "AG1" },
  { label: "Antigua and barbuda : VAT Number", value: "AG2" },
  { label: "Algeria : Income Tax Number", value: "DZ1" },
  { label: "Anguilla : VAT Number", value: "AI2" },
  { label: "Albania : Income Tax Number", value: "AL1" },
  { label: "Albania : VAT Number", value: "AL2" },
  { label: "Armenia : Income Tax Number", value: "AM1" },
  { label: "Netherlands Antilles : Inc Tax Number", value: "AN1" },
  { label: "Netherlands Antilles : VAT Number", value: "AN2" },
  { label: "Anguilla : Income Tax Number", value: "AI1" },
  { label: "Angola : VAT Number", value: "AO2" },
  { label: "Angola : Income Tax Number", value: "AO1" },
  { label: "Austria: VAT Registration Number", value: "AT0" },
  { label: "Australia : Income Tax Number", value: "AU1" },
  { label: "Norway: Tax Number", value: "NO2" },
  { label: "Aruba : Income Tax Number", value: "AW1" },
  { label: "Aruba : VAT Number", value: "AW2" },
  { label: "Azerbaijan : Income Tax Number", value: "AZ1" },
  { label: "Azerbaijan : VAT Number", value: "AZ2" },
  { label: "Bosnia and herzegovina:  Inc Tax Number", value: "BA1" },
  { label: "Oman : VAT Number", value: "OM2" },
  { label: "Australia : VAT Number", value: "AU2" },
  { label: "Bosnia and herzegovina: VAT Number", value: "BA2" },
  { label: "Belgium : Income Tax Number", value: "BE3" },
  { label: "Palestinian  : VAT Number", value: "PS2" },
  { label: "Barbados :  Income Tax Number", value: "BB1" },
  { label: "Barbados : VAT Number", value: "BB2" },
  { label: "Bangladesh :  Income Tax Number", value: "BD1" },
  { label: "Ghana : Income Tax Number", value: "GH1" },
  { label: "Bangladesh : VAT Number", value: "BD2" },
  { label: "Nicaragua : Income Tax Number", value: "NI1" },
  { label: "Belgium: VAT Registration Number", value: "BE0" },
  { label: "Burkina faso : Income Tax Number", value: "BF1" },
  { label: "Virgin Islands : Income Tax Number", value: "VI1" },
  { label: "Bulgaria : Income Tax Number", value: "BG4" },
  { label: "Egypt : Income Tax Number", value: "EG1" },
  { label: "Burkina faso : VAT Number", value: "BF2" },
  { label: "Bulgaria : VAT Number", value: "BG5" },
  { label: "Bahrain : Income Tax Number", value: "BH1" },
  { label: "Portugal: VAT Registration Number", value: "PT0" },
  { label: "Bahrain : VAT Number", value: "BH2" },
  { label: "The dem rep of congo : Income Tax Number", value: "CD1" },
  { label: "Burundi : Income Tax Number", value: "BI1" },
  { label: "Burundi : VAT Number", value: "BI2" },
  { label: "Benin : Income Tax Number", value: "BJ1" },
  { label: "Benin : VAT Number", value: "BJ2" },
  { label: "Bermuda : Income Tax Number", value: "BM1" },
  { label: "Bermuda : VAT Number", value: "BM2" },
  { label: "Brunei darussalam: Income Tax Number", value: "BN1" },
  { label: "Cook islands : Income Tax Number", value: "CK1" },
  { label: "Bolivia : VAT Number", value: "BO2" },
  { label: "Cook islands : VAT Number", value: "CK2" },
  { label: "Bonaire : Income Tax Number", value: "BQ1" },
  { label: "Bahamas : Income Tax Number", value: "BS1" },
  { label: "Sierra leone : VAT Number", value: "SL2" },
  { label: "Bonaire : VAT Number", value: "BQ2" },
  { label: "Bahamas : VAT Number", value: "BS2" },
  { label: "Bhutan : Income Tax Number", value: "BT1" },
  { label: "Mongolia : Income Tax Number", value: "MN1" },
  { label: "Bhutan : VAT Number", value: "BT2" },
  { label: "Liberia : VAT Number", value: "LR2" },
  { label: "Sudan : VAT Number", value: "SD2" },
  { label: "Bouvet island : Income Tax Number", value: "BV1" },
  { label: "Norway: VAT Number", value: "NO1" },
  { label: "Bouvet island : VAT Number", value: "BV2" },
  { label: "Belarus : Income Tax Number", value: "BY1" },
  { label: "Belarus : VAT Number", value: "BY2" },
  { label: "Belize : Income Tax Number", value: "BZ1" },
  { label: "Macao : Income Tax Number", value: "MO1" },
  { label: "Canada : Income Tax Number", value: "CA0" },
  { label: "Central african rep. : Income Tax Number", value: "CF1" },
  { label: "Central african rep. : VAT Number", value: "CF2" },
  { label: "Congo : Income Tax Number", value: "CG1" },
  { label: "Congo : VAT Number", value: "CG2" },
  { label: "Switzerland: Income Tax Number", value: "CH0" },
  { label: "The dem rep of congo : VAT Number", value: "CD2" },
  { label: "Switzerland: UID Number", value: "CH1" },
  { label: "Cote d`ivoire : Income Tax Number", value: "CI1" },
  { label: "Cote d`ivoire : VAT Number", value: "CI2" },
  { label: "Reunion : Income Tax Number", value: "RE1" },
  { label: "Chile : Income Tax Number", value: "CL0" },
  { label: "Chile : VAT Number", value: "CL2" },
  { label: "Cameroon : Income Tax Number", value: "CM1" },
  { label: "Cameroon : VAT Number", value: "CM2" },
  { label: "Japan : Income Tax Number", value: "JP1" },
  { label: "Costa rica : Income Tax Number", value: "CR1" },
  { label: "Cuba : VAT Number", value: "CU2" },
  { label: "Cape verde : Income Tax Number", value: "CV1" },
  { label: "Cape verde : VAT Number", value: "CV2" },
  { label: "Niue : VAT Number", value: "NU2" },
  { label: "Curacao : Income Tax Number", value: "CW1" },
  { label: "Curacao : VAT Number", value: "CW2" },
  { label: "Iraq : VAT Number", value: "IQ2" },
  { label: "Iran : VAT Number", value: "IR2" },
  { label: "Macedonia, form yugoslav rep: Inc Tax No", value: "MK1" },
  { label: "Cyprus: Income Tax Number", value: "CY1" },
  { label: "Cyprus: VAT Registration Number", value: "CY0" },
  { label: "Djibouti : Income Tax Number", value: "DJ1" },
  { label: "Djibouti : VAT Number", value: "DJ2" },
  { label: "India: Tax Identification Number (TIN)", value: "IN2" },
  { label: "LATVIA: VAT REGISTRATION NUMBER", value: "LV0" },
  { label: "Dominica : Income Tax Number", value: "DM1" },
  { label: "Ecuador : VAT Number", value: "EC2" },
  { label: "Dominica : VAT Number", value: "DM2" },
  { label: "Dominican republic : Income Tax Number", value: "DO1" },
  { label: "Dominican republic : VAT Number", value: "DO2" },
  { label: "Uruguay : VAT Number", value: "UY2" },
  { label: "Algeria : VAT Number", value: "DZ2" },
  { label: "Ecuador : Income Tax Number", value: "EC1" },
  { label: "Estonia: Income Tax Number", value: "EE1" },
  { label: "Estonia: VAT Registration Number", value: "EE0" },
  { label: "Egypt : VAT Number", value: "EG2" },
  { label: "Eritrea : Income Tax Number", value: "ER1" },
  { label: "Eritrea : VAT Number", value: "ER2" },
  { label: "Spain: Income Tax Number", value: "ES2" },
  { label: "Spain: VAT Registration Number", value: "ES0" },
  { label: "Ethiopia : VAT Number", value: "ET2" },
  { label: "Kenya : Income Tax Number", value: "KE1" },
  { label: "Fiji : Income Tax Number", value: "FJ1" },
  { label: "Fiji : VAT Number", value: "FJ2" },
  { label: "Gabon : Income Tax Number", value: "GA1" },
  { label: "Guernsey, c.i. : VAT Number", value: "GG2" },
  { label: "Ghana : VAT Number", value: "GH2" },
  { label: "Gibraltar : Income Tax Number", value: "GI1" },
  { label: "Gibraltar : VAT Number", value: "GI2" },
  { label: "Greenland : Income Tax Number", value: "GL1" },
  { label: "Greenland : VAT Number", value: "GL2" },
  { label: "Vietnam : Income Tax Number", value: "VN1" },
  { label: "Gambia : Income Tax Number", value: "GM1" },
  { label: "Portugal: Income Tax Number", value: "PT1" },
  { label: "Gambia : VAT Number", value: "GM2" },
  { label: "Guinea : Income Tax Number", value: "GN1" },
  { label: "Equatorial guinea : Income Tax Number", value: "GQ1" },
  { label: "Equatorial guinea : VAT Number", value: "GQ2" },
  { label: "Saudi arabia : Income Tax Number", value: "SA1" },
  { label: "Vietnam : VAT Number", value: "VN2" },
  { label: "Greece: Income Tax Number", value: "GR3" },
  { label: "Greece: VAT Registration Number", value: "GR0" },
  { label: "Tajikistan : Income Tax Number", value: "TJ1" },
  { label: "Guatemala : VAT Number", value: "GT2" },
  { label: "Guinea-bissau : Income Tax Number", value: "GW1" },
  { label: "Lebanon : VAT Number", value: "LB2" },
  { label: "Guinea-bissau : VAT Number", value: "GW2" },
  { label: "Haiti : Income Tax Number", value: "HT1" },
  { label: "Kazakhstan: VAT Number", value: "KZ3" },
  { label: "Guyana : Income Tax Number", value: "GY1" },
  { label: "Guyana : VAT Number", value: "GY2" },
  { label: "Honduras : Income Tax Number", value: "HN1" },
  { label: "Malta: Income Tax Number", value: "MT1" },
  { label: "Croatia : Income Tax Number", value: "HR3" },
  { label: "Croatia : VAT Number", value: "HR0" },
  { label: "CHINA: VAT REGISTRATION NUMBER", value: "CN0" },
  { label: "Haiti : VAT Number", value: "HT2" },
  { label: "Hungary: Tax Number", value: "HU1" },
  { label: "Hungary: VAT Registration Number", value: "HU0" },
  { label: "Trinidad and Tobago : VAT Number", value: "TT2" },
  { label: "Israel: Income Tax Number", value: "IL1" },
  { label: "Mauritania : VAT Number", value: "MR2" },
  { label: "Israel: VAT Registration Number", value: "IL0" },
  { label: "Jersey, c.i. : VAT Number", value: "JE2" },
  { label: "Isle of man : VAT Number", value: "IM2" },
  { label: "Maldives : Income Tax Number", value: "MV1" },
  { label: "Pakistan : Income Tax Number", value: "PK1" },
  { label: "Iraq : Income Tax Number", value: "IQ1" },
  { label: "Iran : Income Tax Number", value: "IR1" },
  { label: "Iceland : Income Tax Number", value: "IS1" },
  { label: "Iceland : VAT Number", value: "IS2" },
  { label: "Jordan : Income Tax Number", value: "JO1" },
  { label: "Jersey, c.i. : Income Tax Number", value: "JE1" },
  { label: "Jamaica : Income Tax Number", value: "JM1" },
  { label: "Jamaica : VAT Number", value: "JM2" },
  { label: "Kyrgyzstan : VAT Number", value: "KG2" },
  { label: "Jordan : VAT Number", value: "JO2" },
  { label: "Japan : VAT Number", value: "JP2" },
  { label: "Kyrgyzstan : Income Tax Number", value: "KG1" },
  { label: "Cambodia : Income Tax Number", value: "KH1" },
  { label: "Cambodia : VAT Number", value: "KH2" },
  { label: "Comoros : Income Tax Number", value: "KM1" },
  { label: "Saint kitts and nevis : Inc Tax Number", value: "KN1" },
  { label: "Saint kitts and nevis : VAT Number", value: "KN2" },
  { label: "Korea : Income Tax Number", value: "KP1" },
  { label: "New zealand : VAT Number", value: "NZ2" },
  { label: "Korea : VAT Number", value: "KP2" },
  { label: "Mexico : VAT Number", value: "MX5" },
  { label: "Kuwait : VAT Number", value: "KW2" },
  { label: "Marshall islands : VAT Number", value: "MH2" },
  { label: "Mauritania : Income Tax Number", value: "MR1" },
  { label: "Kuwait : Income Tax Number", value: "KW1" },
  { label: "Comoros : VAT Number", value: "KM2" },
  { label: "Lebanon : Income Tax Number", value: "LB1" },
  { label: "Kazakhstan: Income Tax Number", value: "KZ0" },
  { label: "Marshall islands : Income Tax Number", value: "MH1" },
  { label: "Lao  : Income Tax Number", value: "LA1" },
  { label: "Lao  : VAT Number", value: "LA2" },
  { label: "St lucia : Income Tax Number", value: "LC1" },
  { label: "Malaysia : Income Tax Number", value: "MY1" },
  { label: "Turkey: Tax number", value: "TR2" },
  { label: "St lucia : VAT Number", value: "LC2" },
  { label: "Sierra leone : Income Tax Number", value: "SL1" },
  { label: "Liechtenstein : Income Tax Number", value: "LI1" },
  { label: "Macao : VAT Number", value: "MO2" },
  { label: "Montserrat : VAT Number", value: "MS2" },
  { label: "Papua new guinea : Income Tax Number", value: "PG1" },
  { label: "Liechtenstein : VAT Number", value: "LI2" },
  { label: "Sri lanka : VAT Number", value: "LK2" },
  { label: "Saudi arabia : VAT Number", value: "SA2" },
  { label: "Sri lanka : Income Tax Number", value: "LK1" },
  { label: "Lithuania: Income Tax Number", value: "LT1" },
  { label: "Liberia : Income Tax Number", value: "LR1" },
  { label: "Lithuania: VAT Registration Number", value: "LT0" },
  { label: "Luxembourg: Income Tax Number", value: "LU1" },
  { label: "Libya : Income Tax Number", value: "LY1" },
  { label: "Luxembourg: VAT Registration Number", value: "LU0" },
  { label: "Libya : VAT Number", value: "LY2" },
  { label: "Morocco : Income Tax Number", value: "MA1" },
  { label: "Poland: Income Tax Number", value: "PL2" },
  { label: "Morocco : VAT Number", value: "MA2" },
  { label: "Monaco: Income Tax Number", value: "MC1" },
  { label: "French polynesia : Income Tax Number", value: "PF1" },
  { label: "Monaco: VAT Registration Number", value: "MC0" },
  { label: "Moldova, republic of : VAT Number", value: "MD2" },
  { label: "Montenegro : Income Tax Number", value: "ME1" },
  { label: "Palestinian  : Income Tax Number", value: "PS1" },
  { label: "Ukraine : VAT Number", value: "UA5" },
  { label: "Montenegro : VAT Number", value: "ME2" },
  { label: "Madagascar : Income Tax Number", value: "MG1" },
  { label: "Peru : Income Tax Number", value: "PE0" },
  { label: "Moldova, republic of : Inc Tax Number", value: "MD1" },
  { label: "Madagascar : VAT Number", value: "MG2" },
  { label: "Republic of Serbia : VAT Number", value: "RS2" },
  { label: "Macedonia, form yugoslav rep: VAT No", value: "MK2" },
  { label: "Mali : Income Tax Number", value: "ML1" },
  { label: "Mali : VAT Number", value: "ML2" },
  { label: "Mongolia : VAT Number", value: "MN2" },
  { label: "Montserrat : Income Tax Number", value: "MS1" },
  { label: "Malta: VAT Registration Number", value: "MT0" },
  { label: "Maldives : VAT Number", value: "MV2" },
  { label: "Malawi : VAT Number", value: "MW2" },
  { label: "Malawi : Income Tax Number", value: "MW1" },
  { label: "Mexico : Income Tax Number", value: "MX4" },
  { label: "Malaysia : VAT Number", value: "MY2" },
  { label: "Niger : Income Tax Number", value: "NE1" },
  { label: "Nigeria : Income Tax Number", value: "NG1" },
  { label: "Nicaragua : VAT Number", value: "NI2" },
  { label: "Saint vincent and grenadines: Inc Tax No", value: "VC1" },
  { label: "Nepal : Income Tax Number", value: "NP1" },
  { label: "Nepal : VAT Number", value: "NP2" },
  { label: "Niue : Income Tax Number", value: "NU1" },
  { label: "Sweden: VAT Registration Number", value: "SE0" },
  { label: "New zealand : Income Tax Number", value: "NZ0" },
  { label: "Oman : Income Tax Number", value: "OM1" },
  { label: "Panama : Income Tax Number", value: "PA1" },
  { label: "Panama : VAT Number", value: "PA2" },
  { label: "Peru : VAT Number", value: "PE2" },
  { label: "French polynesia : VAT Number", value: "PF2" },
  { label: "Papua new guinea : VAT Number", value: "PG2" },
  { label: "GEORGIA: INCOME TAX", value: "GE3" },
  { label: "Pakistan : VAT Number", value: "PK2" },
  { label: "Poland: VAT Registration Number", value: "PL0" },
  { label: "Puerto rico : Income Tax Number", value: "PR1" },
  { label: "Puerto rico : VAT Number", value: "PR2" },
  { label: "Paraguay : Income Tax Number", value: "PY1" },
  { label: "Paraguay : VAT Number", value: "PY2" },
  { label: "Qatar : Income Tax Number", value: "QA1" },
  { label: "Qatar : VAT Number", value: "QA2" },
  { label: "Reunion : VAT Number", value: "RE2" },
  { label: "Rwanda : Income Tax Number", value: "RW1" },
  { label: "Rwanda : VAT Number", value: "RW2" },
  { label: "Republic of Serbia : Income Tax Number", value: "RS1" },
  { label: "Solomon Islands : Income Tax Number", value: "SB1" },
  { label: "Solomon Islands : VAT Number", value: "SB2" },
  { label: "Sudan : Income Tax Number", value: "SD1" },
  { label: "Seychelles : Income Tax Number", value: "SC1" },
  { label: "Netherlands: Loonbelastingnummer", value: "NL3" },
  { label: "Seychelles : VAT Number", value: "SC2" },
  { label: "Sweden: Income Tax Number", value: "SE1" },
  { label: "Singapore : Income Tax Number", value: "SG3" },
  { label: "Singapore : VAT Number", value: "SG2" },
  { label: "Slovakia: Income Tax Number", value: "SK3" },
  { label: "Slovakia: VAT Registration Number", value: "SK0" },
  { label: "Senegal : Income Tax Number", value: "SN1" },
  { label: "Senegal : VAT Number", value: "SN2" },
  { label: "Somalia : Income Tax Number", value: "SO1" },
  { label: "Somalia : VAT Number", value: "SO2" },
  { label: "South Sudan : Income Tax Number", value: "SS1" },
  { label: "South Sudan : VAT Number", value: "SS2" },
  { label: "El salvador : VAT Number", value: "SV2" },
  { label: "El salvador : Income Tax Number", value: "SV1" },
  { label: "Syrian Arab Rep. : Income Tax Number", value: "SY1" },
  { label: "Kosovo : Income Tax Number", value: "XK1" },
  { label: "Syrian Arab Rep. : VAT Number", value: "SY2" },
  { label: "Turks and caicos islands: Inc Tax Number", value: "TC1" },
  { label: "Turks and caicos islands : VAT Number", value: "TC2" },
  { label: "Brazil: CPF Number", value: "BR2" },
  { label: "Chad : Income Tax Number", value: "TD1" },
  { label: "Slovenia: Tax Number", value: "SI1" },
  { label: "Chad : VAT Number", value: "TD2" },
  { label: "Togo : Income Tax Number", value: "TG1" },
  { label: "Togo : VAT Number", value: "TG2" },
  { label: "Thailand: Income Tax Number", value: "TH0" },
  { label: "Thailand: VAT Number", value: "TH2" },
  { label: "Tunisia : VAT Number", value: "TN2" },
  { label: "Tajikistan : VAT Number", value: "TJ2" },
  { label: "Virgin Islands : VAT Number", value: "VI2" },
  { label: "France: SIREN Number", value: "FR2" },
  { label: "Tunisia : Income Tax Number", value: "TN1" },
  { label: "Tonga : VAT Number", value: "TO2" },
  { label: "Tonga : Income Tax Number", value: "TO1" },
  { label: "Turkey: VAT number", value: "TR0" },
  { label: "Trinidad and Tobago : Income Tax Number", value: "TT1" },
  { label: "Ukraine : Income Tax Number", value: "UA4" },
  { label: "Uruguay : Income Tax Number", value: "UY1" },
  { label: "Uzbekistan : Income Tax Number", value: "UZ1" },
  { label: "Uzbekistan : VAT Number", value: "UZ2" },
  { label: "Venezuela: Income Tax Number", value: "VE3" },
  { label: "Venezuela: VAT Number", value: "VE4" },
  { label: "Vanuatu : Income Tax Number", value: "VU1" },
  { label: "Vanuatu : VAT Number", value: "VU2" },
  { label: "Samoa : Income Tax Number", value: "WS1" },
  { label: "Samoa : VAT Number", value: "WS2" },
  { label: "Kosovo : VAT Number", value: "XK2" },
  { label: "Zimbabwe : Income Tax Number", value: "ZW1" },
  { label: "Zimbabwe : VAT Number", value: "ZW2" },
  { label: "FINLAND: INCOME TAX", value: "FI1" },
  { label: "SIRET NUMBER", value: "FR1" },
  { label: "HONG KONG: INCOME TAX", value: "HK2" },
  { label: "IRELAND: INCOME TAX", value: "IE1" },
  { label: "Netherlands: Income Tax", value: "NL1" },
  { label: "US Tax Identification Number", value: "US01" },
  { label: "Brazil: CNPJ Number", value: "BR1" },
  { label: "Czech Republic: ICO Number", value: "CZ2" },
  { label: "Germany: Income Tax Number", value: "DE1" },
  { label: "United Kingdom: Unique Tax Reference", value: "GB4" },
  { label: "FRANCE: INCOME TAX", value: "FR3" },
  { label: "CZECH REPUBLIC: VAT REGISTRATION NUMBER", value: "CZ0" },
  { label: "ROMANIA: VAT REGISTRATION NUMBER", value: "RO0" },
  { label: "SWITZERLAND: VAT NUMBER", value: "CH2" },
];

/** Sheet: NATURE_OF_BUSINESS */
export const natureOfBusinessOptions: SelectOption[] = [
  { label: "Third Party Fund Administrators", value: "29" },
  { label: "Escort Agencies", value: "11" },
  { label: "Legal Entity in SA with one of the Directors being a Foreigner", value: "2" },
  { label: "Government entities", value: "5" },
  { label: "Cross border risks", value: "3" },
  { label: "Arms and ammunition manufacturing", value: "6" },
  { label: "Financial institutions", value: "4" },
  { label: "Cannabis related activities", value: "27" },
  { label: "Utilities", value: "8" },
  { label: "Gentleman's Estate/Brothels", value: "10" },
  { label: "Pornography goods/stores (referred to Reputational Committee)", value: "9" },
  { label: "Financing of assets located outside the country of booking", value: "1" },
  { label: "Unregistered Financials Services & Credit Providers", value: "12" },
  { label: "Guest Houses (Hospitality)", value: "13" },
  { label: "Educational Institutions (Private & Public)", value: "15" },
  { label: "Houses of Worship", value: "14" },
  { label: "Business Originators (Bond Originators)", value: "16" },
  { label: "Medical/Health Clinics/Hospital", value: "17" },
  { label: "Alternative Medical Service Providers", value: "18" },
  { label: "Labour Brokers", value: "19" },
  { label: "NGO's & NPOs", value: "20" },
  { label: "Money Services Business", value: "21" },
  { label: "Casinos", value: "22" },
  { label: "Authorised Dealer with Limited Authority", value: "25" },
  { label: "Crypto currency exchanges", value: "23" },
  { label: "Embassies", value: "24" },
  { label: "None of the above", value: "999" },
  { label: "Other Gambling entities excl casinos", value: "28" },
  { label: "Attorneys", value: "26" },
  { label: "SBSA Subsidiaries", value: "30" },
];


export const merchantCommissionRates = {
  lowTurnover: {
    sb: { dr: 1.00, cr: 1.99, fr: 3.15 },
    nonSb: { dr: 2.50, cr: 2.50, fr: 3.15 }
  },
  highTurnover: {
    sb: { dr: 0.85, cr: 1.84, fr: 3.00 },
    nonSb: { dr: 2.35, cr: 2.35, fr: 3.00 },
  }
}